CREATE PROCEDURE [dbo].[DELETEDOPPELTEAUSGABEN]
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @AUSGABEID as varchar(40)
	DECLARE @EXEMPLARID as varchar(40)

	DECLARE Double_Cursor CURSOR FOR
	SELECT AUSGABE_ID, EXEMPLAR_ID FROM AUSGABE A
	GROUP BY AUSGABE_ID, EXEMPLAR_ID
	HAVING COUNT(AUSGABE_ID) > 1

	OPEN Double_Cursor;

	FETCH NEXT FROM Double_Cursor INTO @AUSGABEID, @EXEMPLARID;
	WHILE @@FETCH_STATUS = 0
	BEGIN
		WITH a AS
        (
			SELECT TOP 1 *
			FROM  AUSGABE
			WHERE AUSGABE_ID=@AUSGABEID AND EXEMPLAR_ID=@EXEMPLARID
        /* You may want to add ORDER BY here */
        ) DELETE FROM a

		FETCH NEXT FROM Double_Cursor INTO @AUSGABEID, @EXEMPLARID;
	END;            
	CLOSE Double_Cursor;
	DEALLOCATE Double_Cursor;
END;

CREATE PROCEDURE [dbo].[SCHLUESSELNUMMEREXISTS]
  @SCHLUESSELNUMMER VARCHAR(20),
  @ANLAGE_ID VARCHAR(40),
  @SCHLUESSELART INT = NULL,
  @IGN_SCHLUESSEL_ID VARCHAR(40) = NULL,
  @LOCATETRESULT VARCHAR(40) OUT
AS
BEGIN
	 SET NOCOUNT ON
  DECLARE @RETURN_VALUE INT = 0
  SET @LOCATETRESULT = (SELECT MAX(s.SCHLUESSEL_ID) FROM dbo.SCHLUESSEL s
  WHERE s.SCHLUESSELNUMMER COLLATE SQL_Latin1_General_CP1_CS_AS = @SCHLUESSELNUMMER
  AND s.ANLAGE_ID = @ANLAGE_ID
  AND ((NOT @IGN_SCHLUESSEL_ID IS NULL AND s.SCHLUESSEL_ID <> @IGN_SCHLUESSEL_ID) OR (@IGN_SCHLUESSEL_ID IS NULL))
  AND ((NOT @SCHLUESSELART IS NULL AND s.SCHLUESSELART = @SCHLUESSELART) OR (@SCHLUESSELART IS NULL)))
  IF @LOCATETRESULT = NULL
    RETURN 0
  ELSE
    RETURN 1
END;