-- DROP SCHEMA dbo;

CREATE SCHEMA dbo;
-- portier.dbo.ANLAGE definition

-- Drop table

-- DROP TABLE portier.dbo.ANLAGE;

CREATE TABLE portier.dbo.ANLAGE (
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ANLAGE_NR int NULL,
	KOMPETENZSTUFE_ID int NULL,
	ANLAGENUMMER varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEZEICHNUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	AUSGABEZONE_ID int NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLIESSANLAGE varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	HERSTELLER varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGENART varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGENNUMMER varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SYSTEM] varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEANGELEGTAM datetime NULL,
	SACHBEARBEITER_ID varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	TEMP_ID int NULL,
	TRANSFERFLAG int NULL,
	WERK varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_ANLAGE PRIMARY KEY (ANLAGE_ID)
);


-- portier.dbo.AUSFUEHRUNG definition

-- Drop table

-- DROP TABLE portier.dbo.AUSFUEHRUNG;

CREATE TABLE portier.dbo.AUSFUEHRUNG (
	AUSFUEHRUNG_ID int NOT NULL,
	BEZEICHNUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	CONSTRAINT PK_AUSFUEHRUNG PRIMARY KEY (AUSFUEHRUNG_ID)
);


-- portier.dbo.AUSGABE definition

-- Drop table

-- DROP TABLE portier.dbo.AUSGABE;

CREATE TABLE portier.dbo.AUSGABE (
	AUSGABE_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EXEMPLAR_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PERSONAL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BUND_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSEL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	AUSGABE_NR int NULL,
	GFUNKTION_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	AUSGABEDATUM datetime NULL,
	AUSGABEUHR varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RUECKGABETERMINDATUM datetime NULL,
	RUECKGABETERMINUHR varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSELNUMMER varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	AUSGABEVORGANG int NULL,
	PENDENT int NULL,
	UNTERSCHRIFT_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_ID_ABHOLER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	TEMP_ID int NULL,
	PFAND float NULL,
	CONSTRAINT PK_AUSGABE PRIMARY KEY (EXEMPLAR_ID,AUSGABE_ID)
);
 CREATE NONCLUSTERED INDEX IDX_AUSGABE_EID ON dbo.AUSGABE (  EXEMPLAR_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_AUSGABE_PID ON dbo.AUSGABE (  PERSONAL_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_AUSGABE_SID ON dbo.AUSGABE (  SCHLUESSEL_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_AUSGABE_SN ON dbo.AUSGABE (  SCHLUESSELNUMMER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- portier.dbo.AUSGABEHISTORIE definition

-- Drop table

-- DROP TABLE portier.dbo.AUSGABEHISTORIE;

CREATE TABLE portier.dbo.AUSGABEHISTORIE (
	AUSGABEHISTORIE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AUSGABE_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXEMPLAR_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSEL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	AUSGABEDATUM datetime NULL,
	AUSGABEUHR varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	AUSGABE_NR int NULL,
	BUND_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSELNUMMER varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RUECKGABEDATUM datetime NULL,
	RUECKGABEUHR varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_RUECK_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PENDENT int NULL,
	EXEMPLARSTATUS_ID int NULL,
	AUSGABEVORGANG int NULL,
	UNTERSCHRIFT_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_ID_ABHOLER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PFAND float NULL,
	CONSTRAINT PK_AUSGABEHISTORIE PRIMARY KEY (AUSGABEHISTORIE_ID)
);
 CREATE NONCLUSTERED INDEX IDX_AUSGABEHISTORIE_EID ON dbo.AUSGABEHISTORIE (  EXEMPLAR_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_AUSGABEHISTORIE_PID ON dbo.AUSGABEHISTORIE (  PERSONAL_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_AUSGABEHISTORIE_SID ON dbo.AUSGABEHISTORIE (  SCHLUESSEL_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_AUSGABEHISTORIE_SN ON dbo.AUSGABEHISTORIE (  SCHLUESSELNUMMER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- portier.dbo.AUSGABE_APP definition

-- Drop table

-- DROP TABLE portier.dbo.AUSGABE_APP;

CREATE TABLE portier.dbo.AUSGABE_APP (
	AUSGABE_APP_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PERSONAL_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BUND_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SCHLUESSEL_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DEVICE_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	UNTERSCHRIFT_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANFRAGEDATUM datetime NOT NULL,
	ANFRAGEUHR varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	RUECKGABETERMINDATUM datetime NULL,
	RUECKGABETERMINUHR varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNTERSCHRIFTDATUM varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNTERSCHRIFTUHR varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PENDENT varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BILDUNTERSCHRIFT varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PFAND_IST varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NOT NULL,
	LETZTEAENDERUNG datetime NOT NULL,
	CONSTRAINT PK_AUSGABE_APP PRIMARY KEY (AUSGABE_APP_ID)
);


-- portier.dbo.AUSGABE_GV definition

-- Drop table

-- DROP TABLE portier.dbo.AUSGABE_GV;

CREATE TABLE portier.dbo.AUSGABE_GV (
	AUSGABE_GV_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AUSGABE_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANFRAGEDATUM datetime NULL,
	ANFRAGEUHR varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GENEHMIGUNGSDATUM varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GENEHMIGUNGSUHR varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GV_PERSONAL_ID_GENEHMIGT varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GENEHMIGUNGSART varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GENEHMIGUNGSVORGANG int NULL,
	AUSGABEDOKUMENT varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FUNKTIONSDOKUMENT1 varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	CONSTRAINT PK_AUSGABE_GV PRIMARY KEY (AUSGABE_GV_ID)
);


-- portier.dbo.AUSGABE_SIWOS definition

-- Drop table

-- DROP TABLE portier.dbo.AUSGABE_SIWOS;

CREATE TABLE portier.dbo.AUSGABE_SIWOS (
	AUSGABE_SIWOS_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ANTRAGS_ART varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANTRAGSNUMMER_SIWOS varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_ID_ANTRAGSTELLER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_NR_ANTRAGSTELLER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_ID_GENEHMIGER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_NR_GENEHMIGER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_ID_UMSCHREIBER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_NR_UMSCHREIBER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_ID_ABHOLER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_NR_ABHOLER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BUND_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSEL_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXEMPLAR_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZYLINDER_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGE varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSELNUMMER varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXEMPLARNUMMER int NULL,
	AUSFUEHRUNG varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ABMESSUNG_LINKS varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ABMESSUNG_RECHTS varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FAERBUNG varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TUERNUMMER varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TUERNUMMERNEU varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RAUMBEZEICHNUNG varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RAUMBEZEICHNUNGNEU varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANTRAGSDATUM datetime NULL,
	ANTRAGSUHR varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS_MAIL varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RESERVIERUNG_BIS varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NOT NULL,
	LETZTEAENDERUNG datetime NOT NULL,
	CONSTRAINT PK_AUSGABE_SIWOS PRIMARY KEY (AUSGABE_SIWOS_ID)
);


-- portier.dbo.AUSGABE_SIWOS_ARCHIV definition

-- Drop table

-- DROP TABLE portier.dbo.AUSGABE_SIWOS_ARCHIV;

CREATE TABLE portier.dbo.AUSGABE_SIWOS_ARCHIV (
	AUSGABE_SIWOS_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ANTRAGS_ART varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANTRAGSNUMMER_SIWOS varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_ID_ANTRAGSTELLER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_NR_ANTRAGSTELLER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_ID_GENEHMIGER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_NR_GENEHMIGER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_ID_UMSCHREIBER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_NR_UMSCHREIBER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_ID_ABHOLER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERSONAL_NR_ABHOLER varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BUND_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSEL_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXEMPLAR_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZYLINDER_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGE varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSELNUMMER varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXEMPLARNUMMER int NULL,
	AUSFUEHRUNG varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ABMESSUNG_LINKS varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ABMESSUNG_RECHTS varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FAERBUNG varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TUERNUMMER varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TUERNUMMERNEU varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RAUMBEZEICHNUNG varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RAUMBEZEICHNUNGNEU varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANTRAGSDATUM datetime NULL,
	ANTRAGSUHR varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS_MAIL varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RESERVIERUNG_BIS varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NOT NULL,
	LETZTEAENDERUNG datetime NOT NULL,
	SIWOS_GEN_ID float NOT NULL,
	CONSTRAINT PK_AUSGABE_SIWOS_ARCHIV PRIMARY KEY (AUSGABE_SIWOS_ID)
);


-- portier.dbo.BENUTZER definition

-- Drop table

-- DROP TABLE portier.dbo.BENUTZER;

CREATE TABLE portier.dbo.BENUTZER (
	BENUTZER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BENUTZER_NR int NULL,
	USER_KZ varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SYSTEMUSER int NULL,
	VIPUSER int NULL,
	NACHNAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	VORNAME varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PASSWORT varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERS_FRAGE varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERS_ANTWORT varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ABTEILUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RAUM varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TELEFON varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EMAIL varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	INAKTIV int NULL,
	MENUE int NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TEMP_ID int NULL,
	PW1 varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PW2 varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PW3 varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PW4 varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PW5 varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PW6 varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PW7 varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PW8 varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PW9 varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PWD datetime NULL,
	CONSTRAINT PK_BENUTZER PRIMARY KEY (BENUTZER_ID)
);


-- portier.dbo.BESTELLKOPF definition

-- Drop table

-- DROP TABLE portier.dbo.BESTELLKOPF;

CREATE TABLE portier.dbo.BESTELLKOPF (
	BESTELLKOPF_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BESTELLKOPF_NR int NULL,
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	HAENDLER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BESTELLNUMMER varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KOMMISSIONSNUMMER varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZUSATZ_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZUSATZ_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZUSATZ_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BESTELLDATUM datetime NULL,
	LIEFERTERMIN datetime NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIEFER_NAME varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIEFER_ZUSATZ varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIEFER_STRASSE varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIEFER_LKZ varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIEFER_PLZ varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIEFER_ORT varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BESTELLART varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KUNDENNUMMER varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BUCHUNGSDATUM datetime NULL,
	SICHERUNGSKARTE varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	SK_Anlage varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SK_System varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SK_Anlagenart varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SK_Kartennummer varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SK_Hersteller varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SK_Ausstellungsdatum varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SK_Kartenstring varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SK_PIN varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SK_TAN varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SK_USBID varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SK_KUNDENNUMMER varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SK_HDLID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SK_EingabeArt varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_BESTELLKOPF PRIMARY KEY (BESTELLKOPF_ID)
);


-- portier.dbo.BESTELLPOSITION definition

-- Drop table

-- DROP TABLE portier.dbo.BESTELLPOSITION;

CREATE TABLE portier.dbo.BESTELLPOSITION (
	BESTELLPOSITION_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BESTELLPOSITION_NR int NULL,
	BESTELLKOPF_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSEL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZYLINDER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SORTPOSITION smallint NULL,
	BESTELLT smallint NULL,
	GELIEFERT smallint NULL,
	GESAMT smallint NULL,
	NUMMER varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BESCHREIBUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LIEFERDATUM datetime NULL,
	BUCHUNGSDATUM datetime NULL,
	ZUSATZ_1 varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZUSATZ_2 varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZBESTELLT smallint NULL,
	ZGELIEFERT smallint NULL,
	ZGESAMT smallint NULL,
	SCHLUESSELART varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	CONSTRAINT PK_BESTELLPOSITION PRIMARY KEY (BESTELLPOSITION_ID)
);
 CREATE NONCLUSTERED INDEX IDX_BESTELLPOSITION_BID ON dbo.BESTELLPOSITION (  BESTELLKOPF_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_BESTELLPOSITION_SID ON dbo.BESTELLPOSITION (  SCHLUESSEL_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_BESTELLPOSITION_ZID ON dbo.BESTELLPOSITION (  ZYLINDER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- portier.dbo.BUND definition

-- Drop table

-- DROP TABLE portier.dbo.BUND;

CREATE TABLE portier.dbo.BUND (
	BUND_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BUND_NR int NULL,
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZEITZONE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KOMPETENZSTUFE_ID int NULL,
	EXEMPLARSTATUS_ID int NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	QUITTUNGSART_ID int NULL,
	BUNDNUMMER varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BESCHREIBUNG varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ABTEILUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEREICH varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KOSTENSTELLE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DEPOT_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	PFAND int NULL,
	ANSCHAFFUNG int NULL,
	WAEHRUNG varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TEMP_ID int NULL,
	CONSTRAINT PK_BUND PRIMARY KEY (BUND_ID)
);


-- portier.dbo.CADPLAN definition

-- Drop table

-- DROP TABLE portier.dbo.CADPLAN;

CREATE TABLE portier.dbo.CADPLAN (
	CADPLAN_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CADPLAN_NR int NULL,
	GEBAEUDE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PLANNAME varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PFAD varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCALE] float NULL,
	SCHRIFT_HOEHE float NULL,
	FARBE int NULL,
	LAYER int NULL,
	PLAN_BLOB varbinary(MAX) NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	CONSTRAINT PK_CADPLAN PRIMARY KEY (CADPLAN_ID)
);


-- portier.dbo.CUSTOMIZE definition

-- Drop table

-- DROP TABLE portier.dbo.CUSTOMIZE;

CREATE TABLE portier.dbo.CUSTOMIZE (
	CUSTOMIZE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CUSTOMIZE_NR int NULL,
	BEZEICHNUNG varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WERT varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	WERT_BLOB varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_CUSTOMIZE PRIMARY KEY (CUSTOMIZE_ID)
);
 CREATE NONCLUSTERED INDEX IDX_CUSTOMIZE_BEZ ON dbo.CUSTOMIZE (  BEZEICHNUNG ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- portier.dbo.DATEIARCHIV definition

-- Drop table

-- DROP TABLE portier.dbo.DATEIARCHIV;

CREATE TABLE portier.dbo.DATEIARCHIV (
	ARCHIVE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BESCHREIBUNG varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	KATEGORIE varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STICHWORT varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DATEINAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DATUM datetime NULL,
	PERSONAL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DATEIARCHIV_PFAD varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	USER_KZ varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	CONSTRAINT PK_DATEIARCHIV PRIMARY KEY (ARCHIVE_ID)
);


-- portier.dbo.DEPOT definition

-- Drop table

-- DROP TABLE portier.dbo.DEPOT;

CREATE TABLE portier.dbo.DEPOT (
	DEPOT_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DEPOT_NR int NULL,
	DEPOTNUMMER int NULL,
	BEZEICHNUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STRASSE varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LKZ varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PLZ varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ORT varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TELEFON varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FAX varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FUNK varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EMAIL varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KOMPETENZSTUFE_ID int NULL,
	STATUS int NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	TEMP_ID int NULL,
	CONSTRAINT PK_DEPOT PRIMARY KEY (DEPOT_ID)
);


-- portier.dbo.EXEMPLAR definition

-- Drop table

-- DROP TABLE portier.dbo.EXEMPLAR;

CREATE TABLE portier.dbo.EXEMPLAR (
	EXEMPLAR_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EXEMPLAR_NR int NULL,
	BUND_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KOMPETENZSTUFE_ID int NULL,
	SCHLUESSEL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RESERVIERUNG_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
	AUSGABE_SIWOS_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
	SCHLUESSELNUMMER varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXEMPLARSTATUS_ID int NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DEPOT_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DEPOTSTATUS int NULL,
	SONDERBESCHRIFTUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXEMPLAR_BEZEICHNUNG varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	EXEMPLARNUMMER int NULL,
	ANLAGEDATUM datetime NULL,
	TEMP_ID int NULL,
	ausgabe_gv_id varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	AUSGABE_APP_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TRANSFERFLAG int NULL,
	CONSTRAINT PK_EXEMPLAR PRIMARY KEY (EXEMPLAR_ID)
);
 CREATE NONCLUSTERED INDEX IDX_EXEMPLAR_SID ON dbo.EXEMPLAR (  SCHLUESSEL_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_EXEMPLAR_SN ON dbo.EXEMPLAR (  SCHLUESSELNUMMER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_Schluessel_ID ON dbo.EXEMPLAR (  SCHLUESSEL_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- portier.dbo.EXEMPLARSTATUS definition

-- Drop table

-- DROP TABLE portier.dbo.EXEMPLARSTATUS;

CREATE TABLE portier.dbo.EXEMPLARSTATUS (
	EXEMPLARSTATUS_ID int NOT NULL,
	BEZEICHNUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	CONSTRAINT PK_EXEMPLARSTATUS PRIMARY KEY (EXEMPLARSTATUS_ID)
);


-- portier.dbo.GEBAEUDE definition

-- Drop table

-- DROP TABLE portier.dbo.GEBAEUDE;

CREATE TABLE portier.dbo.GEBAEUDE (
	GEBAEUDE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	GEBAEUDE_NR int NULL,
	BEZEICHNUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GEBAEUDETEIL varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PLZ varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ORT varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LKZ varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STRASSE varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	TEMP_ID int NULL,
	GEBAEUDE_FREMD_ID varchar(65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_GEBAEUDE PRIMARY KEY (GEBAEUDE_ID)
);


-- portier.dbo.GFUNKTION definition

-- Drop table

-- DROP TABLE portier.dbo.GFUNKTION;

CREATE TABLE portier.dbo.GFUNKTION (
	GFUNKTION_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	GFUNKTION_NR int NULL,
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSELNUMMER_DEF varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSELNUMMER_AUS varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSELNUMMER_IN varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GFUNKTION varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KZ_VERARBEITUNG varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	ZEITZONE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TEMP_ID int NULL,
	EXTERNFLAG varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_GFUNKTION PRIMARY KEY (GFUNKTION_ID)
);
 CREATE NONCLUSTERED INDEX IDX_GFUNKTION_AID ON dbo.GFUNKTION (  ANLAGE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_GFUNKTION_AID_SNA ON dbo.GFUNKTION (  ANLAGE_ID ASC  , SCHLUESSELNUMMER_AUS ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_GFUNKTION_AID_SND ON dbo.GFUNKTION (  ANLAGE_ID ASC  , SCHLUESSELNUMMER_DEF ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_GFUNKTION_AID_SNI ON dbo.GFUNKTION (  ANLAGE_ID ASC  , SCHLUESSELNUMMER_IN ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_SCHLUESSELNUMMER_AUS ON dbo.GFUNKTION (  SCHLUESSELNUMMER_AUS ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_SCHLUESSELNUMMER_IN ON dbo.GFUNKTION (  SCHLUESSELNUMMER_IN ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- portier.dbo.GRUPPE definition

-- Drop table

-- DROP TABLE portier.dbo.GRUPPE;

CREATE TABLE portier.dbo.GRUPPE (
	GRUPPE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	GRUPPE_NR int NULL,
	GRUPPENNUMMER int NULL,
	BEZEICHNUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	CONSTRAINT PK_GRUPPE PRIMARY KEY (GRUPPE_ID)
);


-- portier.dbo.HAENDLER definition

-- Drop table

-- DROP TABLE portier.dbo.HAENDLER;

CREATE TABLE portier.dbo.HAENDLER (
	HAENDLER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	HAENDLER_NR int NULL,
	HAENDLERNUMMER varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KUNDENNUMMER varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NAME_1 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NAME_2 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANREDE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZUSATZ varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STRASSE varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LKZ varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PLZ varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ORT varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TELEFON varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FUNK varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FAX varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EMAIL varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WEB varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	HAENDLER_SEIT datetime NULL,
	NAMEANSPRECHPARTNER varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TELEFONANSPRECHPARTNER varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEBESTELLUNG datetime NULL,
	BEMERKUNG varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANSPRECHPARTNER varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	HDL_BEST_MAIL varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	HDL_BEST_KEY varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	HDL_BEST_Heandler_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_HAENDLER PRIMARY KEY (HAENDLER_ID)
);


-- portier.dbo.JOURNAL definition

-- Drop table

-- DROP TABLE portier.dbo.JOURNAL;

CREATE TABLE portier.dbo.JOURNAL (
	AKTION varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TABELLE varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NR varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SPALTE varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WERT varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WERTALT varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BENUTZER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL
);


-- portier.dbo.KOMPETENZSTUFE definition

-- Drop table

-- DROP TABLE portier.dbo.KOMPETENZSTUFE;

CREATE TABLE portier.dbo.KOMPETENZSTUFE (
	KOMPETENZSTUFE_ID int NOT NULL,
	BEZEICHNUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	CONSTRAINT PK_KOMPETENZSTUFE PRIMARY KEY (KOMPETENZSTUFE_ID)
);


-- portier.dbo.LOGDATA definition

-- Drop table

-- DROP TABLE portier.dbo.LOGDATA;

CREATE TABLE portier.dbo.LOGDATA (
	LOG_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ANTRAGSNUMMER_SIWOS varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SERVICECALL varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REQUESTDATE datetime NULL,
	REQUESTTIME varchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REQUESTXML varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RESPONCEDATE datetime NULL,
	RESPONCETIME varchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RESPONCEXML varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ERRORSTATUS varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ERRORMESSAGE varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_LOGDATA PRIMARY KEY (LOG_ID)
);


-- portier.dbo.PERSONAL definition

-- Drop table

-- DROP TABLE portier.dbo.PERSONAL;

CREATE TABLE portier.dbo.PERSONAL (
	PERSONAL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PERSONAL_NR int NULL,
	VIPSTUFE_ID int NULL,
	KOMPETENZSTUFE_ID int NULL,
	PERSONALNUMMER varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SUCHBEGRIFF varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANREDE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NAME_1 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NAME_2 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZUSATZ varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STRASSE varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LKZ varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PLZ varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ORT varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GEBURTSDATUM datetime NULL,
	VORLAGEDATUM datetime NULL,
	ABTEILUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEREICH varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KOSTENSTELLE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TAETIGKEIT varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RAUM varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MITARBEITERGRUPPE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZEITZONE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TELEFONPRIVAT varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TELEFONFIRMA varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FAX varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FUNK varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EMAIL varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WEB varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEGINNDATUM datetime NULL,
	BEGINNUHR varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ENDEDATUM datetime NULL,
	ENDEUHR varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PIN varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	QUITTUNGSART_ID int NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	TEMP_ID int NULL,
	RFID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Genehmigerstatus varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TRANSFERFLAG int NULL,
	CONSTRAINT PK_PERSONAL PRIMARY KEY (PERSONAL_ID)
);
 CREATE NONCLUSTERED INDEX IDX_PERSONAL_NA1 ON dbo.PERSONAL (  NAME_1 ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_PERSONAL_NA2 ON dbo.PERSONAL (  NAME_2 ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_PERSONAL_PNR ON dbo.PERSONAL (  PERSONALNUMMER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_PERSONAL_SU ON dbo.PERSONAL (  SUCHBEGRIFF ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- portier.dbo.PERSONALBILD definition

-- Drop table

-- DROP TABLE portier.dbo.PERSONALBILD;

CREATE TABLE portier.dbo.PERSONALBILD (
	PERSONALBILD_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	BILD varbinary(MAX) NULL,
	CONSTRAINT PK_PERSONALBILD PRIMARY KEY (PERSONALBILD_ID)
);


-- portier.dbo.PERSONAL_GV definition

-- Drop table

-- DROP TABLE portier.dbo.PERSONAL_GV;

CREATE TABLE portier.dbo.PERSONAL_GV (
	PERSONAL_GV_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PERSONAL_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DBFELD varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WERT varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	CONSTRAINT PK_PERSONAL_GV PRIMARY KEY (PERSONAL_GV_ID)
);


-- portier.dbo.QUICK_QUERIES definition

-- Drop table

-- DROP TABLE portier.dbo.QUICK_QUERIES;

CREATE TABLE portier.dbo.QUICK_QUERIES (
	QUICK_QUERY_ID int IDENTITY(1,1) NOT NULL,
	BENUTZER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GEBAEUDE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ART varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	QUERY_NAME varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	QUERY_PARAMS nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	CONSTRAINT PK_QUICK_QUERIES PRIMARY KEY (QUICK_QUERY_ID)
);


-- portier.dbo.QUITTUNGSART definition

-- Drop table

-- DROP TABLE portier.dbo.QUITTUNGSART;

CREATE TABLE portier.dbo.QUITTUNGSART (
	QUITTUNGSART_ID int NOT NULL,
	BEZEICHNUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	CONSTRAINT PK_QUITTUNGSART PRIMARY KEY (QUITTUNGSART_ID)
);


-- portier.dbo.REPORT definition

-- Drop table

-- DROP TABLE portier.dbo.REPORT;

CREATE TABLE portier.dbo.REPORT (
	REPORT_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	REPORT_NR int NULL,
	REPORTART int NULL,
	GRUPPE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STEUERUNG int NULL,
	REPORT_AENDERBAR int NULL,
	SQL_TEXT varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	REPORTNUMMER varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_REPORT PRIMARY KEY (REPORT_ID)
);


-- portier.dbo.REPORT_BIN definition

-- Drop table

-- DROP TABLE portier.dbo.REPORT_BIN;

CREATE TABLE portier.dbo.REPORT_BIN (
	REPORT_BIN_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	REPORT_BIN_NR int NULL,
	REPORT_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SPRACHE_ID int NOT NULL,
	BESCHREIBUNG varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REPORT_PFAD varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REPORT_BIN varbinary(MAX) NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REPORT_VARIANTE int NOT NULL,
	CONSTRAINT PK_REPORT_BIN PRIMARY KEY (REPORT_BIN_ID)
);


-- portier.dbo.RE_ANLAGE_BUND definition

-- Drop table

-- DROP TABLE portier.dbo.RE_ANLAGE_BUND;

CREATE TABLE portier.dbo.RE_ANLAGE_BUND (
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BUND_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_ANLAGE_BUND PRIMARY KEY (ANLAGE_ID,BUND_ID)
);


-- portier.dbo.RE_ANLAGE_DEPOT definition

-- Drop table

-- DROP TABLE portier.dbo.RE_ANLAGE_DEPOT;

CREATE TABLE portier.dbo.RE_ANLAGE_DEPOT (
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DEPOT_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_ANLAGE_DEPOT PRIMARY KEY (ANLAGE_ID,DEPOT_ID)
);


-- portier.dbo.RE_ANLAGE_GEBAEUDE definition

-- Drop table

-- DROP TABLE portier.dbo.RE_ANLAGE_GEBAEUDE;

CREATE TABLE portier.dbo.RE_ANLAGE_GEBAEUDE (
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	GEBAEUDE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_ANLAGE_GEBAEUDE PRIMARY KEY (ANLAGE_ID,GEBAEUDE_ID)
);


-- portier.dbo.RE_ANLAGE_PERSONAL definition

-- Drop table

-- DROP TABLE portier.dbo.RE_ANLAGE_PERSONAL;

CREATE TABLE portier.dbo.RE_ANLAGE_PERSONAL (
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PERSONAL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_ANLAGE_PERSONAL PRIMARY KEY (ANLAGE_ID,PERSONAL_ID)
);


-- portier.dbo.RE_ANLAGE_ROLLE definition

-- Drop table

-- DROP TABLE portier.dbo.RE_ANLAGE_ROLLE;

CREATE TABLE portier.dbo.RE_ANLAGE_ROLLE (
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ROLLE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_ANLAGE_ROLLE PRIMARY KEY (ANLAGE_ID,ROLLE_ID)
);


-- portier.dbo.RE_ANLAGE_ROLLE_BENUTZER definition

-- Drop table

-- DROP TABLE portier.dbo.RE_ANLAGE_ROLLE_BENUTZER;

CREATE TABLE portier.dbo.RE_ANLAGE_ROLLE_BENUTZER (
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ROLLE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BENUTZER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	KOMPETENZSTUFE_ID int NULL,
	CONSTRAINT PK_RE_ANLAGE_ROLLE_BENUTZER PRIMARY KEY (ANLAGE_ID,ROLLE_ID,BENUTZER_ID)
);


-- portier.dbo.RE_AUSGABE_GV_EXEMPLAR definition

-- Drop table

-- DROP TABLE portier.dbo.RE_AUSGABE_GV_EXEMPLAR;

CREATE TABLE portier.dbo.RE_AUSGABE_GV_EXEMPLAR (
	AUSGABE_GV_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AUSGABE_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EXEMPLAR_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_AUSGABE_GV_EXEMPLAR PRIMARY KEY (AUSGABE_GV_ID,AUSGABE_ID,EXEMPLAR_ID)
);


-- portier.dbo.RE_AUSGABE_GV_PERSONAL definition

-- Drop table

-- DROP TABLE portier.dbo.RE_AUSGABE_GV_PERSONAL;

CREATE TABLE portier.dbo.RE_AUSGABE_GV_PERSONAL (
	AUSGABE_GV_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AUSGABE_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PERSONAL_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_AUSGABE_GV_PERSONAL PRIMARY KEY (AUSGABE_GV_ID,AUSGABE_ID,PERSONAL_ID)
);


-- portier.dbo.RE_BENUTZER_DEPOT definition

-- Drop table

-- DROP TABLE portier.dbo.RE_BENUTZER_DEPOT;

CREATE TABLE portier.dbo.RE_BENUTZER_DEPOT (
	BENUTZER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DEPOT_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_BENUTZER_DEPOT PRIMARY KEY (DEPOT_ID,BENUTZER_ID)
);


-- portier.dbo.RE_BENUTZER_STANDORT definition

-- Drop table

-- DROP TABLE portier.dbo.RE_BENUTZER_STANDORT;

CREATE TABLE portier.dbo.RE_BENUTZER_STANDORT (
	BENUTZER_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	STANDORT_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_BENUTZER_STANDORT PRIMARY KEY (BENUTZER_ID,STANDORT_ID)
);


-- portier.dbo.RE_BENUTZER_TILE_STRUCTURE definition

-- Drop table

-- DROP TABLE portier.dbo.RE_BENUTZER_TILE_STRUCTURE;

CREATE TABLE portier.dbo.RE_BENUTZER_TILE_STRUCTURE (
	TILE_ID int IDENTITY(1,1) NOT NULL,
	BENUTZER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ANLAGE_GEBAUDE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGE_GEBAUDE_BEZEICHNUNG varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SYSTEMUSER int DEFAULT 0 NULL,
	ROLLE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TILE_STRUCTURE varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	CONSTRAINT PK__RE_BENUT__411A8FC9FCFE1F50 PRIMARY KEY (TILE_ID)
);


-- portier.dbo.RE_BUND_DEISTER definition

-- Drop table

-- DROP TABLE portier.dbo.RE_BUND_DEISTER;

CREATE TABLE portier.dbo.RE_BUND_DEISTER (
	BUND_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BUND_NR int NULL,
	KEYTAG_ID int NULL,
	CABINET_ID int NULL,
	SLOT_NUMBER int NULL,
	TRANSPONDERSTATE int NULL,
	TERMINAL_DISPLAYNAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MAKE varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MODEL varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SERIALNUMBER varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RESPONSIBLEEMAIL varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENTTERMINALUSERIDKEEPER int NULL,
	CONSTRAINT PK_RE_BUND_DEISTER PRIMARY KEY (BUND_ID)
);


-- portier.dbo.RE_EXEMPLAR_DEISTER definition

-- Drop table

-- DROP TABLE portier.dbo.RE_EXEMPLAR_DEISTER;

CREATE TABLE portier.dbo.RE_EXEMPLAR_DEISTER (
	EXEMPLAR_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EXEMPLAR_NR int NULL,
	CABINET_ID int NULL,
	SLOT_NUMBER int NULL,
	TRANSPONDERSTATE int NULL,
	KEYTAG_ID int NULL,
	TERMINAL_DISPLAYNAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MAKE varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MODEL varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SERIALNUMBER varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RESPONSIBLEEMAIL varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CURRENTTERMINALUSERIDKEEPER int NULL,
	CONSTRAINT PK_RE_EXEMPLAR_DEISTER PRIMARY KEY (EXEMPLAR_ID)
);


-- portier.dbo.RE_GEBAEUDE_BUND definition

-- Drop table

-- DROP TABLE portier.dbo.RE_GEBAEUDE_BUND;

CREATE TABLE portier.dbo.RE_GEBAEUDE_BUND (
	GEBAEUDE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BUND_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_GEBAEUDE_BUND PRIMARY KEY (BUND_ID,GEBAEUDE_ID)
);


-- portier.dbo.RE_GEBAEUDE_DEPOT definition

-- Drop table

-- DROP TABLE portier.dbo.RE_GEBAEUDE_DEPOT;

CREATE TABLE portier.dbo.RE_GEBAEUDE_DEPOT (
	GEBAEUDE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DEPOT_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_GEBAEUDE_DEPOT PRIMARY KEY (DEPOT_ID,GEBAEUDE_ID)
);


-- portier.dbo.RE_GEBAEUDE_PERSONAL definition

-- Drop table

-- DROP TABLE portier.dbo.RE_GEBAEUDE_PERSONAL;

CREATE TABLE portier.dbo.RE_GEBAEUDE_PERSONAL (
	GEBAEUDE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PERSONAL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_GEBAEUDE_PERSONAL PRIMARY KEY (GEBAEUDE_ID,PERSONAL_ID)
);


-- portier.dbo.RE_GEBAEUDE_ROLLE definition

-- Drop table

-- DROP TABLE portier.dbo.RE_GEBAEUDE_ROLLE;

CREATE TABLE portier.dbo.RE_GEBAEUDE_ROLLE (
	GEBAEUDE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ROLLE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_GEBAEUDE_ROLLE PRIMARY KEY (GEBAEUDE_ID,ROLLE_ID)
);


-- portier.dbo.RE_GEBAEUDE_ROLLE_BENUTZER definition

-- Drop table

-- DROP TABLE portier.dbo.RE_GEBAEUDE_ROLLE_BENUTZER;

CREATE TABLE portier.dbo.RE_GEBAEUDE_ROLLE_BENUTZER (
	GEBAEUDE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ROLLE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BENUTZER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	KOMPETENZSTUFE_ID int NULL,
	CONSTRAINT PK_RE_GEBAEUDE_ROLLE_BENUTZER PRIMARY KEY (GEBAEUDE_ID,ROLLE_ID,BENUTZER_ID)
);


-- portier.dbo.RE_PERSONAL_DEISTER definition

-- Drop table

-- DROP TABLE portier.dbo.RE_PERSONAL_DEISTER;

CREATE TABLE portier.dbo.RE_PERSONAL_DEISTER (
	TERMINAL_USER_ID int NULL,
	PERSONAL_DEISTER_NR int NOT NULL,
	PERSONAL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PERSONAL_NR int NULL,
	TERMINAL_ANZEIGE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_RE_PERSONAL_DEISTER PRIMARY KEY (PERSONAL_DEISTER_NR)
);


-- portier.dbo.RE_PERSONAL_GRUPPE definition

-- Drop table

-- DROP TABLE portier.dbo.RE_PERSONAL_GRUPPE;

CREATE TABLE portier.dbo.RE_PERSONAL_GRUPPE (
	PERSONAL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	GRUPPE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_PERSONAL_GRUPPE PRIMARY KEY (PERSONAL_ID,GRUPPE_ID)
);


-- portier.dbo.RE_PERSONAL_STANDORT definition

-- Drop table

-- DROP TABLE portier.dbo.RE_PERSONAL_STANDORT;

CREATE TABLE portier.dbo.RE_PERSONAL_STANDORT (
	PERSONAL_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	STANDORT_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_PERSONAL_STANDORT PRIMARY KEY (PERSONAL_ID,STANDORT_ID)
);


-- portier.dbo.RE_SCHLUESSEL_GRUPPE definition

-- Drop table

-- DROP TABLE portier.dbo.RE_SCHLUESSEL_GRUPPE;

CREATE TABLE portier.dbo.RE_SCHLUESSEL_GRUPPE (
	SCHLUESSEL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	GRUPPE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_SCHLUESSEL_GRUPPE PRIMARY KEY (SCHLUESSEL_ID,GRUPPE_ID)
);


-- portier.dbo.RE_SCHLUESSEL_ZYLINDER definition

-- Drop table

-- DROP TABLE portier.dbo.RE_SCHLUESSEL_ZYLINDER;

CREATE TABLE portier.dbo.RE_SCHLUESSEL_ZYLINDER (
	SCHLUESSEL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ZYLINDER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_SCHLUESSEL_ZYLINDER PRIMARY KEY (SCHLUESSEL_ID,ZYLINDER_ID)
);
 CREATE NONCLUSTERED INDEX IDX_RE_SCHLUESSEL_ZYLINDER_SID ON dbo.RE_SCHLUESSEL_ZYLINDER (  SCHLUESSEL_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_RE_SCHLUESSEL_ZYLINDER_SID_ZID ON dbo.RE_SCHLUESSEL_ZYLINDER (  SCHLUESSEL_ID ASC  , ZYLINDER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_RE_SCHLUESSEL_ZYLINDER_ZID ON dbo.RE_SCHLUESSEL_ZYLINDER (  ZYLINDER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- portier.dbo.RE_TUER_ZYLINDER definition

-- Drop table

-- DROP TABLE portier.dbo.RE_TUER_ZYLINDER;

CREATE TABLE portier.dbo.RE_TUER_ZYLINDER (
	TUER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ZYLINDER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_TUER_ZYLINDER PRIMARY KEY (TUER_ID,ZYLINDER_ID)
);


-- portier.dbo.RE_ZYLINDER_CADPLAN definition

-- Drop table

-- DROP TABLE portier.dbo.RE_ZYLINDER_CADPLAN;

CREATE TABLE portier.dbo.RE_ZYLINDER_CADPLAN (
	ZYLINDER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CADPLAN_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK_RE_ZYLINDER_CADPLAN PRIMARY KEY (CADPLAN_ID,ZYLINDER_ID)
);
 CREATE NONCLUSTERED INDEX IDX_RE_ZYLINDER_CADPLAN_ZID_CID ON dbo.RE_ZYLINDER_CADPLAN (  ZYLINDER_ID ASC  , CADPLAN_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- portier.dbo.ROLLE definition

-- Drop table

-- DROP TABLE portier.dbo.ROLLE;

CREATE TABLE portier.dbo.ROLLE (
	ROLLE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ROLLE_NR int NULL,
	STUFE int NULL,
	BEZEICHNUNG varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	CONSTRAINT PK_ROLLE PRIMARY KEY (ROLLE_ID)
);


-- portier.dbo.SCHLIESSMATRIX definition

-- Drop table

-- DROP TABLE portier.dbo.SCHLIESSMATRIX;

CREATE TABLE portier.dbo.SCHLIESSMATRIX (
	SCHLIESSMATRIX_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	NUMMER int NULL,
	SCHLIESSMATRIX_NR int NULL,
	BESCHREIBUNG varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PERIODISCH varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DATUMFLAG varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DATUM_SET ntext COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TIME_SET ntext COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FEIER_SET ntext COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	TEMP_ID int NULL,
	CONSTRAINT PK_SCHLIESSMATRIX PRIMARY KEY (SCHLIESSMATRIX_ID)
);


-- portier.dbo.SCHLUESSEL definition

-- Drop table

-- DROP TABLE portier.dbo.SCHLUESSEL;

CREATE TABLE portier.dbo.SCHLUESSEL (
	SCHLUESSEL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SCHLUESSEL_NR int NULL,
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZEITZONE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KOMPETENZSTUFE_ID int NULL,
	UE_KNOTEN int NULL,
	SCHLUESSELNUMMER varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSELNUMMER_ZUSATZ varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSELBESCHREIBUNG varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSELNAME varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSELART smallint NULL,
	SCHLIESSUNGSART smallint NULL,
	SCHLUESSELTYP smallint NULL,
	MINDESTBESTAND int NULL,
	BESTELLVORSCHLAG int NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ARTIKEL_NR varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SORTIERUNG int NULL,
	SONDERBESCHRIFTUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DEPOTFREMD int NULL,
	QUITTUNGSART_ID int NULL,
	PFAND int NULL,
	ANSCHAFFUNG int NULL,
	WAEHRUNG varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TEMP_ID int NULL,
	ERWEITERUNG int NULL,
	SCHLUESSEL_FREMD_ID varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PIN varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WERK varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	EXTERNFLAG varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Sensitiv varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GenehmigungsFlag varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TRANSFERFLAG int NULL,
	CONSTRAINT PK_SCHLUESSEL PRIMARY KEY (SCHLUESSEL_ID)
);
 CREATE NONCLUSTERED INDEX IDX_SCHLUESSEL_AID ON dbo.SCHLUESSEL (  ANLAGE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_SCHLUESSEL_BES ON dbo.SCHLUESSEL (  SCHLUESSELBESCHREIBUNG ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_SCHLUESSEL_SN ON dbo.SCHLUESSEL (  SCHLUESSELNUMMER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- portier.dbo.SCHLUESSEL_SIWOS_DELTA definition

-- Drop table

-- DROP TABLE portier.dbo.SCHLUESSEL_SIWOS_DELTA;

CREATE TABLE portier.dbo.SCHLUESSEL_SIWOS_DELTA (
	SCHLUESSEL_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	WERK varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	HERSTELLER varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLIESSANLAGE varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSELNUMMER varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TRANSFERFLAG int NULL,
	TRANSFERFLAGANLAGE int NULL,
	ANLAGEDATUM datetime NOT NULL,
	LETZTEAENDERUNG datetime NOT NULL,
	CONSTRAINT PK_SCHLUESSEL_SIWOS_DELTA PRIMARY KEY (SCHLUESSEL_ID)
);


-- portier.dbo.STANDORT definition

-- Drop table

-- DROP TABLE portier.dbo.STANDORT;

CREATE TABLE portier.dbo.STANDORT (
	STANDORT_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	STANDORT_NR int NULL,
	STANDORTNUMMER int NULL,
	BEZEICHNUNG varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STRASSE varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LKZ varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PLZ varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ORT varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TELEFON varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FAX varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FUNK varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EMAIL varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS int NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	TEMP_ID int NULL,
	CONSTRAINT PK_STANDORT PRIMARY KEY (STANDORT_ID)
);


-- portier.dbo.SYS_ADDON definition

-- Drop table

-- DROP TABLE portier.dbo.SYS_ADDON;

CREATE TABLE portier.dbo.SYS_ADDON (
	SYS_ADDON_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SYS_ADDON_NR int NULL,
	ART varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BESCHREIBUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROGRAMM varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CODE int NULL,
	HINT varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	A_FELD varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	B_FELD varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	CONSTRAINT PK_SYS_ADDON PRIMARY KEY (SYS_ADDON_ID)
);


-- portier.dbo.SYS_NACHSCHLAGETABELLE definition

-- Drop table

-- DROP TABLE portier.dbo.SYS_NACHSCHLAGETABELLE;

CREATE TABLE portier.dbo.SYS_NACHSCHLAGETABELLE (
	SYS_NACHSCHLAGETABELLE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SYS_NACHSCHLAGETABELLE_NR int NULL,
	ART int NULL,
	BEZEICHNUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WERT varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	CONSTRAINT PK_SYS_NACHSCHLAGETABELLE PRIMARY KEY (SYS_NACHSCHLAGETABELLE_ID)
);


-- portier.dbo.TMP_DRUCK definition

-- Drop table

-- DROP TABLE portier.dbo.TMP_DRUCK;

CREATE TABLE portier.dbo.TMP_DRUCK (
	VORGANG_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	QUELL_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ALTWERT_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NEUWERT_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ALTTEXT varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NEUTEXT varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	AENDERUNGSDATUM datetime NULL,
	ANLAGEDATUM datetime NULL,
	CONSTRAINT PK_TMP_DRUCK PRIMARY KEY (VORGANG_ID,QUELL_ID)
);


-- portier.dbo.TUER definition

-- Drop table

-- DROP TABLE portier.dbo.TUER;

CREATE TABLE portier.dbo.TUER (
	TUER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	GEBAEUDE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TUER_NR int NULL,
	BEZEICHNUNG varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KURZNOTIZ varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TUERNR varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TUERNRELEKTRISCH varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RAUMBEZEICHNUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ABTEILUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEREICH varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KOSTENSTELLE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZUSATZ1 varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZUSATZ2 varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EINBAUSTATUS int NULL,
	TEMP_ID int NULL,
	TUER_FREMD_ID varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	CONSTRAINT PK_TUER PRIMARY KEY (TUER_ID)
);


-- portier.dbo.UNTERSCHRIFT definition

-- Drop table

-- DROP TABLE portier.dbo.UNTERSCHRIFT;

CREATE TABLE portier.dbo.UNTERSCHRIFT (
	UNTERSCHRIFT_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	UNTERSCHRIFT_NR int NULL,
	PERSONAL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	BILD varbinary(MAX) NULL,
	CONSTRAINT PK_UNTERSCHRIFT PRIMARY KEY (UNTERSCHRIFT_ID)
);


-- portier.dbo.VIPSTUFE definition

-- Drop table

-- DROP TABLE portier.dbo.VIPSTUFE;

CREATE TABLE portier.dbo.VIPSTUFE (
	VIPSTUFE_ID int NOT NULL,
	BEZEICHNUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	CONSTRAINT PK_VIPSTUFE PRIMARY KEY (VIPSTUFE_ID)
);


-- portier.dbo.ZEITZONE definition

-- Drop table

-- DROP TABLE portier.dbo.ZEITZONE;

CREATE TABLE portier.dbo.ZEITZONE (
	ZEITZONE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ZEITZONE_NR int NULL,
	ZEITZONENBESCHREIBUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZEITRAUM varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WOCHENTAGE varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TAGESZEIT varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	D1 varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	D2 varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	D3 varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	D4 varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	D5 varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	D6 varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	D7 varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DATUM_VON datetime NULL,
	DATUM_BIS datetime NULL,
	ZEIT_VON varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZEIT_BIS varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	LETZTEAENDERUNG datetime NULL,
	TEMP_ID int NULL,
	CONSTRAINT PK_ZEITZONE PRIMARY KEY (ZEITZONE_ID)
);


-- portier.dbo.ZUGRIFF definition

-- Drop table

-- DROP TABLE portier.dbo.ZUGRIFF;

CREATE TABLE portier.dbo.ZUGRIFF (
	ZUGRIFF_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ZUGRIFF_NR int NULL,
	GRUPPE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	AKTION varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STUFE int NULL,
	KOMPETENZ int NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	CONSTRAINT PK_ZUGRIFF PRIMARY KEY (ZUGRIFF_ID)
);


-- portier.dbo.ZYLINDER definition

-- Drop table

-- DROP TABLE portier.dbo.ZYLINDER;

CREATE TABLE portier.dbo.ZYLINDER (
	ZYLINDER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ZYLINDER_NR int NULL,
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GEBAEUDE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CADPLAN_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KOMPETENZSTUFE_ID int NULL,
	AUSFUEHRUNG_ID int NULL,
	SCHLUESSELNUMMER varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEZEICHNUNG varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GPOSITION varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZYLINDERANZAHL int NULL,
	KURZNOTIZ varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BESTELLVORSCHLAG int NULL,
	TUERNR varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RAUMBEZEICHNUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ABTEILUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEREICH varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KOSTENSTELLE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FAERBUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TUERNRELEKTRISCH varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZUSATZ1 varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZUSATZ2 varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ABMESSUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ABMESSUNG_LINKS numeric(6,1) NULL,
	ABMESSUNG_RECHTS numeric(6,1) NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EINBAUSTATUS int NULL,
	ARTIKEL_NR varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SORTIERUNG numeric(8,2) NULL,
	SONDERAUSFUEHRUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SONDERAUSFUEHRUNG_POS varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SONDER_POS varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	XWERT float NULL,
	YWERT float NULL,
	ZWERT float NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PFAND numeric(8,2) NULL,
	ANSCHAFFUNG numeric(8,2) NULL,
	WAEHRUNG varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TEMP_ID int NULL,
	ERWEITERUNG int NULL,
	ZYLINDER_FREMD_ID varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WERK varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LETZTEAENDERUNG datetime NULL,
	ANLAGEDATUM datetime NULL,
	ARTIKELBESCHREIBUNG varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EXTERNFLAG varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TRANSFERFLAG int NULL,
	SCHLUESSEL_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT '' NULL,
	CONSTRAINT PK_ZYLINDER PRIMARY KEY (ZYLINDER_ID)
);
 CREATE NONCLUSTERED INDEX IDX_ZYLINDER_AID ON dbo.ZYLINDER (  ANLAGE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_ZYLINDER_BEZ ON dbo.ZYLINDER (  BEZEICHNUNG ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_ZYLINDER_GID ON dbo.ZYLINDER (  GEBAEUDE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_ZYLINDER_RAU ON dbo.ZYLINDER (  RAUMBEZEICHNUNG ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_ZYLINDER_SN ON dbo.ZYLINDER (  SCHLUESSELNUMMER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_ZYLINDER_TNR ON dbo.ZYLINDER (  TUERNR ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- portier.dbo.ZYLINDERHISTORIE definition

-- Drop table

-- DROP TABLE portier.dbo.ZYLINDERHISTORIE;

CREATE TABLE portier.dbo.ZYLINDERHISTORIE (
	ZYLINDER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZYLINDER_NR int NULL,
	ANLAGE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GEBAEUDE_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KOMPETENZSTUFE_ID int NULL,
	AUSFUEHRUNG_ID int NULL,
	BEZEICHNUNG varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	GPOSITION varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZYLINDERANZAHL int NULL,
	KURZNOTIZ varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BESTELLVORSCHLAG int NULL,
	TUERNR varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RAUMBEZEICHNUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ABTEILUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEREICH varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	KOSTENSTELLE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FAERBUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TUERNRELEKTRISCH varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZUSATZ1 varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ZUSATZ2 varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ABMESSUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ABMESSUNG_LINKS numeric(6,1) NULL,
	ABMESSUNG_RECHTS numeric(6,1) NULL,
	BEMERKUNG_1 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_2 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BEMERKUNG_3 varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EINBAUSTATUS int NULL,
	ARTIKEL_NR varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SORTIERUNG numeric(8,2) NULL,
	SONDERAUSFUEHRUNG varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SONDERAUSFUEHRUNG_POS varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SONDER_POS varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	XWERT int NULL,
	YWERT int NULL,
	SACHBEARBEITER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ANLAGEDATUM datetime NULL,
	PFAND numeric(8,2) NULL,
	ANSCHAFFUNG numeric(8,2) NULL,
	WAEHRUNG varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);
 CREATE NONCLUSTERED INDEX IDX_ZYLINDERHISTORIE_AID ON dbo.ZYLINDERHISTORIE (  ANLAGE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_ZYLINDERHISTORIE_GID ON dbo.ZYLINDERHISTORIE (  GEBAEUDE_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_ZYLINDERHISTORIE_ZID ON dbo.ZYLINDERHISTORIE (  ZYLINDER_ID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- portier.dbo.ZYLINDER_SIWOS_DELTA definition

-- Drop table

-- DROP TABLE portier.dbo.ZYLINDER_SIWOS_DELTA;

CREATE TABLE portier.dbo.ZYLINDER_SIWOS_DELTA (
	ZYLINDER_ID varchar(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	WERK varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLIESSANLAGE varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SCHLUESSELNUMMER varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATUS varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TRANSFERFLAG int NULL,
	TRANSFERFLAGANLAGE int NULL,
	ANLAGEDATUM datetime NOT NULL,
	LETZTEAENDERUNG datetime NOT NULL,
	CONSTRAINT PK_ZYLINDER_SIWOS_DELTA PRIMARY KEY (ZYLINDER_ID)
);


