CREATE DATABASE portier;

\c portier;

CREATE SCHEMA IF NOT EXISTS dbo;

CREATE EXTENSION pg_stat_statements SCHEMA dbo;

CREATE TABLE IF NOT EXISTS dbo.ACCESS (
  ZUGRIFF_ID varchar PRIMARY KEY,
  ZUGRIFF_NR int,
  GRUPPE varchar,
  AKTION varchar,
  STUFE int,
  KOMPETENZ int,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_ZUGRIFF ON dbo.ACCESS (ZUGRIFF_ID);

CREATE TABLE IF NOT EXISTS dbo.BUILDING (
  GEBAEUDE_ID varchar PRIMARY KEY,
  GEBAEUDE_NR int,
  BEZEICHNUNG varchar,
  GEBAEUDETEIL varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  PLZ varchar,
  ORT varchar,
  LKZ varchar,
  STRASSE varchar,
  SACHBEARBEITER_ID varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  TEMP_ID int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_GEBAEUDE ON dbo.BUILDING (GEBAEUDE_ID);

CREATE TABLE IF NOT EXISTS dbo.BUNDLE (
  BUND_ID varchar PRIMARY KEY,
  BUND_NR int,
  ANLAGE_ID varchar,
  ZEITZONE_ID varchar,
  KOMPETENZSTUFE_ID int,
  EXEMPLARSTATUS_ID int,
  SACHBEARBEITER_ID varchar,
  QUITTUNGSART_ID int,
  BUNDNUMMER varchar,
  BESCHREIBUNG varchar,
  ABTEILUNG varchar,
  BEREICH varchar,
  KOSTENSTELLE varchar,
  DEPOT_ID varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  PFAND int,
  ANSCHAFFUNG int,
  WAEHRUNG varchar,
  TEMP_ID int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_BUND ON dbo.BUNDLE (BUND_ID);

CREATE TABLE IF NOT EXISTS dbo.CADPLAN (
  CADPLAN_ID varchar PRIMARY KEY,
  CADPLAN_NR int,
  GEBAEUDE_ID varchar,
  PLANNAME varchar,
  PFAD varchar,
  SCALE float,
  SCHRIFT_HOEHE float,
  FARBE int,
  LAYER int,
  PLAN_BLOB bytea,
  SACHBEARBEITER_ID varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_CADPLAN ON dbo.CADPLAN (CADPLAN_ID);

CREATE TABLE IF NOT EXISTS dbo.COMPETENCELEVEL (
  KOMPETENZSTUFE_ID int PRIMARY KEY,
  BEZEICHNUNG varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_KOMPETENZSTUFE ON dbo.COMPETENCELEVEL (KOMPETENZSTUFE_ID);

CREATE TABLE IF NOT EXISTS dbo.COPY (
  EXEMPLAR_ID varchar PRIMARY KEY,
  EXEMPLAR_NR int,
  BUND_ID varchar,
  KOMPETENZSTUFE_ID int,
  SCHLUESSEL_ID varchar,
  RESERVIERUNG_ID varchar DEFAULT (''),
  AUSGABE_SIWOS_ID varchar DEFAULT (''),
  SCHLUESSELNUMMER varchar,
  EXEMPLARSTATUS_ID int,
  SACHBEARBEITER_ID varchar,
  DEPOT_ID varchar,
  DEPOTSTATUS int,
  SONDERBESCHRIFTUNG varchar,
  EXEMPLAR_BEZEICHNUNG varchar,
  LETZTEAENDERUNG timestamp,
  EXEMPLARNUMMER int,
  ANLAGEDATUM timestamp,
  TEMP_ID int,
  ausgabe_gv_id varchar,
  AUSGABE_APP_ID varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_EXEMPLAR ON dbo.COPY (EXEMPLAR_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_Schluessel_ID ON dbo.COPY (SCHLUESSEL_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_EXEMPLAR_SN ON dbo.COPY (SCHLUESSELNUMMER);
CREATE INDEX IF NOT EXISTS dbo_IDX_EXEMPLAR_SID ON dbo.COPY (SCHLUESSEL_ID);

CREATE TABLE IF NOT EXISTS dbo.COPYSTATUS (
  EXEMPLARSTATUS_ID int PRIMARY KEY,
  BEZEICHNUNG varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_EXEMPLARSTATUS ON dbo.COPYSTATUS (EXEMPLARSTATUS_ID);

CREATE TABLE IF NOT EXISTS dbo.CUSTOMIZE (
  CUSTOMIZE_ID varchar PRIMARY KEY,
  CUSTOMIZE_NR int,
  BEZEICHNUNG varchar,
  WERT varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  WERT_BLOB varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_CUSTOMIZE ON dbo.CUSTOMIZE (CUSTOMIZE_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_CUSTOMIZE_BEZ ON dbo.CUSTOMIZE (BEZEICHNUNG);

CREATE TABLE IF NOT EXISTS dbo.CYLINDER (
  ZYLINDER_ID varchar PRIMARY KEY,
  ZYLINDER_NR int,
  ANLAGE_ID varchar,
  GEBAEUDE_ID varchar,
  CADPLAN_ID varchar,
  KOMPETENZSTUFE_ID int,
  AUSFUEHRUNG_ID int,
  SCHLUESSELNUMMER varchar,
  BEZEICHNUNG varchar,
  GPOSITION varchar,
  ZYLINDERANZAHL int,
  KURZNOTIZ varchar,
  BESTELLVORSCHLAG int,
  TUERNR varchar,
  RAUMBEZEICHNUNG varchar,
  ABTEILUNG varchar,
  BEREICH varchar,
  KOSTENSTELLE varchar,
  FAERBUNG varchar,
  TUERNRELEKTRISCH varchar,
  ZUSATZ1 varchar,
  ZUSATZ2 varchar,
  ABMESSUNG varchar,
  ABMESSUNG_LINKS numeric(6, 1),
  ABMESSUNG_RECHTS numeric(6, 1),
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  EINBAUSTATUS int,
  ARTIKEL_NR varchar,
  SORTIERUNG numeric(8, 2),
  SONDERAUSFUEHRUNG varchar,
  SONDERAUSFUEHRUNG_POS varchar,
  SONDER_POS varchar,
  XWERT float,
  YWERT float,
  ZWERT float,
  SACHBEARBEITER_ID varchar,
  PFAND numeric(8, 2),
  ANSCHAFFUNG numeric(8, 2),
  WAEHRUNG varchar,
  TEMP_ID int,
  ERWEITERUNG int,
  ZYLINDER_FREMD_ID varchar,
  WERK varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  ARTIKELBESCHREIBUNG varchar,
  EXTERNFLAG varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_ZYLINDER ON dbo.CYLINDER (ZYLINDER_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDER_SN ON dbo.CYLINDER (SCHLUESSELNUMMER);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDER_BEZ ON dbo.CYLINDER (BEZEICHNUNG);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDER_AID ON dbo.CYLINDER (ANLAGE_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDER_GID ON dbo.CYLINDER (GEBAEUDE_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDER_TNR ON dbo.CYLINDER (TUERNR);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDER_RAU ON dbo.CYLINDER (RAUMBEZEICHNUNG);

CREATE TABLE IF NOT EXISTS dbo.CYLINDERHISTORY (
  ZYLINDER_ID varchar,
  ZYLINDER_NR int,
  ANLAGE_ID varchar,
  GEBAEUDE_ID varchar,
  KOMPETENZSTUFE_ID int,
  AUSFUEHRUNG_ID int,
  BEZEICHNUNG varchar,
  GPOSITION varchar,
  ZYLINDERANZAHL int,
  KURZNOTIZ varchar,
  BESTELLVORSCHLAG int,
  TUERNR varchar,
  RAUMBEZEICHNUNG varchar,
  ABTEILUNG varchar,
  BEREICH varchar,
  KOSTENSTELLE varchar,
  FAERBUNG varchar,
  TUERNRELEKTRISCH varchar,
  ZUSATZ1 varchar,
  ZUSATZ2 varchar,
  ABMESSUNG varchar,
  ABMESSUNG_LINKS numeric(6, 1),
  ABMESSUNG_RECHTS numeric(6, 1),
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  EINBAUSTATUS int,
  ARTIKEL_NR varchar,
  SORTIERUNG numeric(8, 2),
  SONDERAUSFUEHRUNG varchar,
  SONDERAUSFUEHRUNG_POS varchar,
  SONDER_POS varchar,
  XWERT int,
  YWERT int,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  PFAND numeric(8, 2),
  ANSCHAFFUNG numeric(8, 2),
  WAEHRUNG varchar
);

CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDERHISTORIE_ZID ON dbo.CYLINDERHISTORY (ZYLINDER_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDERHISTORIE_AID ON dbo.CYLINDERHISTORY (ANLAGE_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDERHISTORIE_GID ON dbo.CYLINDERHISTORY (GEBAEUDE_ID);

CREATE TABLE IF NOT EXISTS dbo.DEALER (
  HAENDLER_ID varchar PRIMARY KEY,
  HAENDLER_NR int,
  HAENDLERNUMMER varchar,
  KUNDENNUMMER varchar,
  NAME_1 varchar,
  NAME_2 varchar,
  ANREDE varchar,
  ZUSATZ varchar,
  STRASSE varchar,
  LKZ varchar,
  PLZ varchar,
  ORT varchar,
  TELEFON varchar,
  FUNK varchar,
  FAX varchar,
  EMAIL varchar,
  WEB varchar,
  HAENDLER_SEIT timestamp,
  NAMEANSPRECHPARTNER varchar,
  TELEFONANSPRECHPARTNER varchar,
  LETZTEBESTELLUNG timestamp,
  BEMERKUNG varchar,
  SACHBEARBEITER_ID varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  ANSPRECHPARTNER varchar,
  HDL_BEST_MAIL varchar,
  HDL_BEST_KEY varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  HDL_BEST_Heandler_ID varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_HAENDLER ON dbo.DEALER (HAENDLER_ID);

CREATE TABLE IF NOT EXISTS dbo.DEPOT (
  DEPOT_ID varchar PRIMARY KEY,
  DEPOT_NR int,
  DEPOTNUMMER int,
  BEZEICHNUNG varchar,
  STRASSE varchar,
  LKZ varchar,
  PLZ varchar,
  ORT varchar,
  TELEFON varchar,
  FAX varchar,
  FUNK varchar,
  EMAIL varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  KOMPETENZSTUFE_ID int,
  STATUS int,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  TEMP_ID int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_DEPOT ON dbo.DEPOT (DEPOT_ID);

CREATE TABLE IF NOT EXISTS dbo.DOOR (
  TUER_ID varchar PRIMARY KEY,
  GEBAEUDE_ID varchar,
  TUER_NR int,
  BEZEICHNUNG varchar,
  KURZNOTIZ varchar,
  TUERNR varchar,
  TUERNRELEKTRISCH varchar,
  RAUMBEZEICHNUNG varchar,
  ABTEILUNG varchar,
  BEREICH varchar,
  KOSTENSTELLE varchar,
  ZUSATZ1 varchar,
  ZUSATZ2 varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  EINBAUSTATUS int,
  TEMP_ID int,
  TUER_FREMD_ID varchar,
  SACHBEARBEITER_ID varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_DOOR ON dbo.DOOR (TUER_ID);

CREATE TABLE IF NOT EXISTS dbo.EXECUTION (
  AUSFUEHRUNG_ID int PRIMARY KEY,
  BEZEICHNUNG varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSFUEHRUNG ON dbo.EXECUTION (AUSFUEHRUNG_ID);

CREATE TABLE IF NOT EXISTS dbo.GFUNCTION (
  GFUNKTION_ID varchar PRIMARY KEY,
  GFUNKTION_NR int,
  ANLAGE_ID varchar,
  SCHLUESSELNUMMER_DEF varchar,
  SCHLUESSELNUMMER_AUS varchar,
  SCHLUESSELNUMMER_IN varchar,
  GFUNKTION varchar,
  KZ_VERARBEITUNG varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  ZEITZONE_ID varchar,
  TEMP_ID int,
  EXTERNFLAG varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_GFUNKTION ON dbo.GFUNCTION (GFUNKTION_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_SCHLUESSELNUMMER_AUS ON dbo.GFUNCTION (SCHLUESSELNUMMER_AUS);
CREATE INDEX IF NOT EXISTS dbo_IDX_SCHLUESSELNUMMER_IN ON dbo.GFUNCTION (SCHLUESSELNUMMER_IN);
CREATE INDEX IF NOT EXISTS dbo_IDX_GFUNKTION_AID ON dbo.GFUNCTION (ANLAGE_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_GFUNKTION_AID_SNA ON dbo.GFUNCTION (ANLAGE_ID, SCHLUESSELNUMMER_AUS);
CREATE INDEX IF NOT EXISTS dbo_IDX_GFUNKTION_AID_SNI ON dbo.GFUNCTION (ANLAGE_ID, SCHLUESSELNUMMER_IN);
CREATE INDEX IF NOT EXISTS dbo_IDX_GFUNKTION_AID_SND ON dbo.GFUNCTION (ANLAGE_ID, SCHLUESSELNUMMER_DEF);

CREATE TABLE IF NOT EXISTS dbo.GROUP (
  GRUPPE_ID varchar PRIMARY KEY,
  GRUPPE_NR int,
  GRUPPENNUMMER int,
  BEZEICHNUNG varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  SACHBEARBEITER_ID varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE TABLE IF NOT EXISTS dbo.ISSUE (
  AUSGABE_ID varchar PRIMARY KEY,
  EXEMPLAR_ID varchar,
  PERSONAL_ID varchar,
  BUND_ID varchar,
  SCHLUESSEL_ID varchar,
  ANLAGE_ID varchar,
  AUSGABE_NR int,
  GFUNKTION_ID varchar,
  SACHBEARBEITER_ID varchar,
  AUSGABEDATUM timestamp,
  AUSGABEUHR varchar,
  RUECKGABETERMINDATUM timestamp,
  RUECKGABETERMINUHR varchar,
  BEMERKUNG varchar,
  STATUS varchar,
  SCHLUESSELNUMMER varchar,
  AUSGABEVORGANG int,
  PENDENT int,
  UNTERSCHRIFT_ID varchar,
  PERSONAL_ID_ABHOLER varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  TEMP_ID int,
  PFAND float
);

CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABE_SN ON dbo.ISSUE (SCHLUESSELNUMMER);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABE_SID ON dbo.ISSUE (SCHLUESSEL_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABE_EID ON dbo.ISSUE (EXEMPLAR_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABE_PID ON dbo.ISSUE (PERSONAL_ID);

CREATE TABLE IF NOT EXISTS dbo.ISSUE_APP (
  AUSGABE_APP_ID varchar PRIMARY KEY,
  PERSONAL_ID varchar,
  BUND_ID varchar,
  SCHLUESSEL_ID varchar,
  DEVICE_ID varchar,
  UNTERSCHRIFT_ID varchar,
  ANFRAGEDATUM timestamp,
  ANFRAGEUHR varchar,
  RUECKGABETERMINDATUM timestamp,
  RUECKGABETERMINUHR varchar,
  UNTERSCHRIFTDATUM varchar,
  UNTERSCHRIFTUHR varchar,
  STATUS varchar,
  PENDENT varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  BILDUNTERSCHRIFT varchar,
  PFAND_IST varchar,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSGABE_APP ON dbo.ISSUE_APP (AUSGABE_APP_ID);

CREATE TABLE IF NOT EXISTS dbo.ISSUE_GV (
  AUSGABE_GV_ID varchar PRIMARY KEY,
  AUSGABE_ID varchar,
  PERSONAL_ID varchar,
  ANFRAGEDATUM timestamp,
  ANFRAGEUHR varchar,
  GENEHMIGUNGSDATUM varchar,
  GENEHMIGUNGSUHR varchar,
  GV_PERSONAL_ID_GENEHMIGT varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  GENEHMIGUNGSART varchar,
  STATUS varchar,
  GENEHMIGUNGSVORGANG int,
  AUSGABEDOKUMENT varchar,
  FUNKTIONSDOKUMENT1 varchar,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE TABLE IF NOT EXISTS dbo.ISSUE_SIWOS (
  AUSGABE_SIWOS_ID varchar PRIMARY KEY,
  ANTRAGS_ART varchar,
  ANTRAGSNUMMER_SIWOS varchar,
  PERSONAL_ID_ANTRAGSTELLER varchar,
  PERSONAL_NR_ANTRAGSTELLER varchar,
  PERSONAL_ID_GENEHMIGER varchar,
  PERSONAL_NR_GENEHMIGER varchar,
  PERSONAL_ID_UMSCHREIBER varchar,
  PERSONAL_NR_UMSCHREIBER varchar,
  PERSONAL_ID_ABHOLER varchar,
  PERSONAL_NR_ABHOLER varchar,
  BUND_ID varchar,
  SCHLUESSEL_ID varchar,
  EXEMPLAR_ID varchar,
  ZYLINDER_ID varchar,
  ANLAGE varchar,
  SCHLUESSELNUMMER varchar,
  EXEMPLARNUMMER int,
  AUSFUEHRUNG varchar,
  ABMESSUNG_LINKS varchar,
  ABMESSUNG_RECHTS varchar,
  FAERBUNG varchar,
  TUERNUMMER varchar,
  TUERNUMMERNEU varchar,
  RAUMBEZEICHNUNG varchar,
  RAUMBEZEICHNUNGNEU varchar,
  ANTRAGSDATUM timestamp,
  ANTRAGSUHR varchar,
  STATUS varchar,
  STATUS_MAIL varchar,
  RESERVIERUNG_BIS varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSGABE_SIWOS ON dbo.ISSUE_SIWOS (AUSGABE_SIWOS_ID);

CREATE TABLE IF NOT EXISTS dbo.ISSUEHISTORY (
  AUSGABEHISTORIE_ID varchar PRIMARY KEY,
  AUSGABE_ID varchar,
  ANLAGE_ID varchar,
  EXEMPLAR_ID varchar,
  PERSONAL_ID varchar,
  SCHLUESSEL_ID varchar,
  AUSGABEDATUM timestamp,
  AUSGABEUHR varchar,
  AUSGABE_NR int,
  BUND_ID varchar,
  SCHLUESSELNUMMER varchar,
  RUECKGABEDATUM timestamp,
  RUECKGABEUHR varchar,
  SACHBEARBEITER_ID varchar,
  SACHBEARBEITER_RUECK_ID varchar,
  BEMERKUNG varchar,
  PENDENT int,
  EXEMPLARSTATUS_ID int,
  AUSGABEVORGANG int,
  UNTERSCHRIFT_ID varchar,
  PERSONAL_ID_ABHOLER varchar,
  PFAND float
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSGABEHISTORIE ON dbo.ISSUEHISTORY (AUSGABEHISTORIE_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABEHISTORIE_SN ON dbo.ISSUEHISTORY (SCHLUESSELNUMMER);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABEHISTORIE_SID ON dbo.ISSUEHISTORY (SCHLUESSEL_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABEHISTORIE_EID ON dbo.ISSUEHISTORY (EXEMPLAR_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABEHISTORIE_PID ON dbo.ISSUEHISTORY (PERSONAL_ID);

CREATE TABLE IF NOT EXISTS dbo.JOURNAL (
  AKTION varchar,
  TABELLE varchar,
  ID varchar,
  NR varchar,
  SPALTE varchar,
  WERT varchar,
  WERTALT varchar,
  BENUTZER_ID varchar,
  ANLAGEDATUM timestamp
);

CREATE TABLE IF NOT EXISTS dbo.KEY (
  SCHLUESSEL_ID varchar PRIMARY KEY,
  SCHLUESSEL_NR int,
  ANLAGE_ID varchar,
  ZEITZONE_ID varchar,
  KOMPETENZSTUFE_ID int,
  UE_KNOTEN int,
  SCHLUESSELNUMMER varchar,
  SCHLUESSELNUMMER_ZUSATZ varchar,
  SCHLUESSELBESCHREIBUNG varchar,
  SCHLUESSELNAME varchar,
  SCHLUESSELART smallint,
  SCHLIESSUNGSART smallint,
  SCHLUESSELTYP smallint,
  MINDESTBESTAND int,
  BESTELLVORSCHLAG int,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  ARTIKEL_NR varchar,
  SACHBEARBEITER_ID varchar,
  SORTIERUNG int,
  SONDERBESCHRIFTUNG varchar,
  DEPOTFREMD int,
  QUITTUNGSART_ID int,
  PFAND int,
  ANSCHAFFUNG int,
  WAEHRUNG varchar,
  TEMP_ID int,
  ERWEITERUNG int,
  SCHLUESSEL_FREMD_ID varchar,
  PIN varchar,
  WERK varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  EXTERNFLAG varchar,
  Sensitiv varchar,
  GenehmigungsFlag varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_SCHLUESSEL ON dbo.KEY (SCHLUESSEL_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_SCHLUESSEL_SN ON dbo.KEY (SCHLUESSELNUMMER);
CREATE INDEX IF NOT EXISTS dbo_IDX_SCHLUESSEL_BES ON dbo.KEY (SCHLUESSELBESCHREIBUNG);
CREATE INDEX IF NOT EXISTS dbo_IDX_SCHLUESSEL_AID ON dbo.KEY (ANLAGE_ID);

CREATE TABLE IF NOT EXISTS dbo.LOCATION (
  STANDORT_ID varchar PRIMARY KEY,
  STANDORT_NR int,
  STANDORTNUMMER int,
  BEZEICHNUNG varchar,
  STRASSE varchar,
  LKZ varchar,
  PLZ varchar,
  ORT varchar,
  TELEFON varchar,
  FAX varchar,
  FUNK varchar,
  EMAIL varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  STATUS int,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  TEMP_ID int
);

CREATE TABLE IF NOT EXISTS dbo.LOCKINGMATRIX (
  SCHLIESSMATRIX_ID varchar,
  NUMMER int,
  SCHLIESSMATRIX_NR int,
  BESCHREIBUNG varchar,
  PERIODISCH varchar,
  DATUMFLAG varchar,
  DATUM_SET text,
  TIME_SET text,
  FEIER_SET text,
  SACHBEARBEITER_ID varchar,
  STATUS varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  TEMP_ID int
);

CREATE TABLE IF NOT EXISTS dbo.ORDERHEAD (
  BESTELLKOPF_ID varchar PRIMARY KEY,
  BESTELLKOPF_NR int,
  ANLAGE_ID varchar,
  HAENDLER_ID varchar,
  SACHBEARBEITER_ID varchar,
  BESTELLNUMMER varchar,
  KOMMISSIONSNUMMER varchar,
  ZUSATZ_1 varchar,
  ZUSATZ_2 varchar,
  ZUSATZ_3 varchar,
  BESTELLDATUM timestamp,
  LIEFERTERMIN timestamp,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  STATUS varchar,
  LIEFER_NAME varchar,
  LIEFER_ZUSATZ varchar,
  LIEFER_STRASSE varchar,
  LIEFER_LKZ varchar,
  LIEFER_PLZ varchar,
  LIEFER_ORT varchar,
  BESTELLART varchar,
  KUNDENNUMMER varchar,
  BUCHUNGSDATUM timestamp,
  SICHERUNGSKARTE varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  SK_Anlage varchar,
  SK_System varchar,
  SK_Anlagenart varchar,
  SK_Kartennummer varchar,
  SK_Hersteller varchar,
  SK_Ausstellungsdatum varchar,
  SK_Kartenstring varchar,
  SK_PIN varchar,
  SK_TAN varchar,
  SK_USBID varchar,
  SK_KUNDENNUMMER varchar,
  SK_HDLID varchar,
  SK_EingabeArt varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_BESTELLKOPF ON dbo.ORDERHEAD (BESTELLKOPF_ID);

CREATE TABLE IF NOT EXISTS dbo.ORDERPOSITION (
  BESTELLPOSITION_ID varchar PRIMARY KEY,
  BESTELLPOSITION_NR int,
  BESTELLKOPF_ID varchar,
  SCHLUESSEL_ID varchar,
  ZYLINDER_ID varchar,
  SORTPOSITION smallint,
  BESTELLT smallint,
  GELIEFERT smallint,
  GESAMT smallint,
  NUMMER varchar,
  BESCHREIBUNG varchar,
  LIEFERDATUM timestamp,
  BUCHUNGSDATUM timestamp,
  ZUSATZ_1 varchar,
  ZUSATZ_2 varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  STATUS varchar,
  ZBESTELLT smallint,
  ZGELIEFERT smallint,
  ZGESAMT smallint,
  SCHLUESSELART varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_BESTELLPOSITION ON dbo.ORDERPOSITION (BESTELLPOSITION_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_BESTELLPOSITION_SID ON dbo.ORDERPOSITION (SCHLUESSEL_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_BESTELLPOSITION_ZID ON dbo.ORDERPOSITION (ZYLINDER_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_BESTELLPOSITION_BID ON dbo.ORDERPOSITION (BESTELLKOPF_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_BUILDING_BUNDLE (
  GEBAEUDE_ID varchar,
  BUND_ID varchar,
  PRIMARY KEY (BUND_ID, GEBAEUDE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_GEBAEUDE_BUND ON dbo.RE_BUILDING_BUNDLE (BUND_ID, GEBAEUDE_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_BUILDING_DEPOT (
  GEBAEUDE_ID varchar,
  DEPOT_ID varchar,
  PRIMARY KEY (DEPOT_ID, GEBAEUDE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_GEBAEUDE_DEPOT ON dbo.RE_BUILDING_DEPOT (DEPOT_ID, GEBAEUDE_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_BUILDING_ROLE (
  GEBAEUDE_ID varchar,
  ROLLE_ID varchar,
  PRIMARY KEY (GEBAEUDE_ID, ROLLE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_GEBAEUDE_ROLLE ON dbo.RE_BUILDING_ROLE (GEBAEUDE_ID, ROLLE_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_BUILDING_ROLE_USER (
  GEBAEUDE_ID varchar,
  ROLLE_ID varchar,
  BENUTZER_ID varchar,
  KOMPETENZSTUFE_ID int,
  PRIMARY KEY (GEBAEUDE_ID, ROLLE_ID, BENUTZER_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_GEBAEUDE_ROLLE_BENUTZER ON dbo.RE_BUILDING_ROLE_USER (GEBAEUDE_ID, ROLLE_ID, BENUTZER_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_BUILDING_STAFF (
  GEBAEUDE_ID varchar,
  PERSONAL_ID varchar,
  PRIMARY KEY (GEBAEUDE_ID, PERSONAL_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_GEBAEUDE_PERSONAL ON dbo.RE_BUILDING_STAFF (GEBAEUDE_ID, PERSONAL_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_BUNDLE_DEISTER (
  BUND_ID varchar,
  BUND_NR int,
  KEYTAG_ID int,
  CABINET_ID int,
  SLOT_NUMBER int,
  TRANSPONDERSTATE int,
  TERMINAL_DISPLAYNAME varchar,
  MAKE varchar,
  MODEL varchar,
  SERIALNUMBER varchar,
  RESPONSIBLEEMAIL varchar,
  CURRENTTERMINALUSERIDKEEPER int
);

CREATE TABLE IF NOT EXISTS dbo.RE_COPY_DEISTER (
  EXEMPLAR_ID varchar,
  EXEMPLAR_NR int,
  CABINET_ID int,
  SLOT_NUMBER int,
  TRANSPONDERSTATE int,
  KEYTAG_ID int,
  TERMINAL_DISPLAYNAME varchar,
  MAKE varchar,
  MODEL varchar,
  SERIALNUMBER varchar,
  RESPONSIBLEEMAIL varchar,
  CURRENTTERMINALUSERIDKEEPER int
);

CREATE TABLE IF NOT EXISTS dbo.RE_CYLINDER_CADPLAN (
  ZYLINDER_ID varchar,
  CADPLAN_ID varchar,
  PRIMARY KEY (CADPLAN_ID, ZYLINDER_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_ZYLINDER_CADPLAN ON dbo.RE_CYLINDER_CADPLAN (CADPLAN_ID, ZYLINDER_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_RE_ZYLINDER_CADPLAN_ZID_CID ON dbo.RE_CYLINDER_CADPLAN (ZYLINDER_ID, CADPLAN_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_ISSUE_GV_COPY (
  AUSGABE_GV_ID varchar,
  AUSGABE_ID varchar,
  EXEMPLAR_ID varchar,
  PRIMARY KEY (AUSGABE_GV_ID, AUSGABE_ID, EXEMPLAR_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSGABE_GV_EXEMPLAR ON dbo.RE_ISSUE_GV_COPY (AUSGABE_GV_ID, AUSGABE_ID, EXEMPLAR_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_ISSUE_GV_STAFF (
  AUSGABE_GV_ID varchar,
  AUSGABE_ID varchar,
  PERSONAL_ID varchar,
  PRIMARY KEY (AUSGABE_GV_ID, AUSGABE_ID, PERSONAL_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSGABE_GV_PERSONAL ON dbo.RE_ISSUE_GV_STAFF (AUSGABE_GV_ID, AUSGABE_ID, PERSONAL_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_KEY_CYLINDER (
  SCHLUESSEL_ID varchar,
  ZYLINDER_ID varchar,
  PRIMARY KEY (SCHLUESSEL_ID, ZYLINDER_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_SCHLUESSEL_ZYLINDER ON dbo.RE_KEY_CYLINDER (SCHLUESSEL_ID, ZYLINDER_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_RE_SCHLUESSEL_ZYLINDER_SID_ZID ON dbo.RE_KEY_CYLINDER (SCHLUESSEL_ID, ZYLINDER_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_RE_SCHLUESSEL_ZYLINDER_SID ON dbo.RE_KEY_CYLINDER (SCHLUESSEL_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_RE_SCHLUESSEL_ZYLINDER_ZID ON dbo.RE_KEY_CYLINDER (ZYLINDER_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_KEY_GROUP (
  SCHLUESSEL_ID varchar,
  GRUPPE_ID varchar
);

CREATE TABLE IF NOT EXISTS dbo.RE_STAFF_DEISTER (
  TERMINAL_USER_ID int,
  PERSONAL_DEISTER_NR int,
  PERSONAL_ID varchar,
  PERSONAL_NR int,
  TERMINAL_ANZEIGE varchar,
  PRIMARY KEY (PERSONAL_DEISTER_NR)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_PERSONAL_DEISTER ON dbo.RE_STAFF_DEISTER (PERSONAL_DEISTER_NR);

CREATE TABLE IF NOT EXISTS dbo.RE_STAFF_GROUP (
  PERSONAL_ID varchar,
  GRUPPE_ID varchar
);

CREATE TABLE IF NOT EXISTS dbo.RE_STAFF_LOCATION (
  PERSONAL_ID varchar,
  STANDORT_ID varchar,
  PRIMARY KEY (PERSONAL_ID, STANDORT_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_PERSONAL_STANDORT ON dbo.RE_STAFF_LOCATION (PERSONAL_ID, STANDORT_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_SYSTEM_BUILDING (
  ANLAGE_ID varchar,
  GEBAEUDE_ID varchar,
  PRIMARY KEY (ANLAGE_ID, GEBAEUDE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_ANLAGE_GEBAEUDE ON dbo.RE_SYSTEM_BUILDING (ANLAGE_ID, GEBAEUDE_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_SYSTEM_BUNDLE (
  ANLAGE_ID varchar,
  BUND_ID varchar,
  PRIMARY KEY (ANLAGE_ID, BUND_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_ANLAGE_BUND ON dbo.RE_SYSTEM_BUNDLE (ANLAGE_ID, BUND_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_SYSTEM_DEPOT (
  ANLAGE_ID varchar,
  DEPOT_ID varchar,
  PRIMARY KEY (ANLAGE_ID, DEPOT_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_ANLAGE_DEPOT ON dbo.RE_SYSTEM_DEPOT (ANLAGE_ID, DEPOT_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_SYSTEM_ROLE (
  ANLAGE_ID varchar,
  ROLLE_ID varchar,
  PRIMARY KEY (ANLAGE_ID, ROLLE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_ANLAGE_ROLLE ON dbo.RE_SYSTEM_ROLE (ANLAGE_ID, ROLLE_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_SYSTEM_STAFF (
  ANLAGE_ID varchar,
  PERSONAL_ID varchar,
  PRIMARY KEY (ANLAGE_ID, PERSONAL_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_ANLAGE_PERSONAL ON dbo.RE_SYSTEM_STAFF (ANLAGE_ID, PERSONAL_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_SYSTEM_USER (
  ANLAGE_ID varchar,
  ROLLE_ID varchar,
  BENUTZER_ID varchar,
  KOMPETENZSTUFE_ID int
);

CREATE TABLE IF NOT EXISTS dbo.RE_USER_DEPOT (
  BENUTZER_ID varchar,
  DEPOT_ID varchar,
  PRIMARY KEY (DEPOT_ID, BENUTZER_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_BENUTZER_DEPOT ON dbo.RE_USER_DEPOT (DEPOT_ID, BENUTZER_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_USER_LOCATION (
  BENUTZER_ID varchar,
  STANDORT_ID varchar,
  PRIMARY KEY (BENUTZER_ID, STANDORT_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_BENUTZER_STANDORT ON dbo.RE_USER_LOCATION (BENUTZER_ID, STANDORT_ID);

CREATE TABLE IF NOT EXISTS dbo.RECEIPTTYPE (
  QUITTUNGSART_ID int PRIMARY KEY,
  BEZEICHNUNG varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_QUITTUNGSART ON dbo.RECEIPTTYPE (QUITTUNGSART_ID);

CREATE TABLE IF NOT EXISTS dbo.REPORT (
  REPORT_ID varchar PRIMARY KEY,
  REPORT_NR int,
  REPORTART int,
  GRUPPE varchar,
  NAME varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  STEUERUNG int,
  REPORT_AENDERBAR int,
  SQL_TEXT varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  REPORTNUMMER varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_REPORT ON dbo.REPORT (REPORT_ID);

CREATE TABLE IF NOT EXISTS dbo.REPORT_BIN (
  REPORT_BIN_ID varchar PRIMARY KEY,
  REPORT_BIN_NR int,
  REPORT_ID varchar,
  SPRACHE_ID int,
  BESCHREIBUNG varchar,
  REPORT_PFAD varchar,
  REPORT_BIN bytea,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  SACHBEARBEITER_ID varchar,
  REPORT_VARIANTE int
);

CREATE TABLE IF NOT EXISTS dbo.ROLE (
  ROLLE_ID varchar PRIMARY KEY,
  ROLLE_NR int,
  STUFE int,
  BEZEICHNUNG varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_ROLLE ON dbo.ROLE (ROLLE_ID);

CREATE TABLE IF NOT EXISTS dbo.SIGNATURE (
  UNTERSCHRIFT_ID varchar PRIMARY KEY,
  UNTERSCHRIFT_NR int,
  PERSONAL_ID varchar,
  SACHBEARBEITER_ID varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  BILD bytea
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_UNTERSCHRIFT ON dbo.SIGNATURE (UNTERSCHRIFT_ID);

CREATE TABLE IF NOT EXISTS dbo.STAFF (
  PERSONAL_ID varchar PRIMARY KEY,
  PERSONAL_NR int,
  VIPSTUFE_ID int,
  KOMPETENZSTUFE_ID int,
  PERSONALNUMMER varchar,
  SUCHBEGRIFF varchar,
  ANREDE varchar,
  NAME_1 varchar,
  NAME_2 varchar,
  ZUSATZ varchar,
  STRASSE varchar,
  LKZ varchar,
  PLZ varchar,
  ORT varchar,
  GEBURTSDATUM timestamp,
  VORLAGEDATUM timestamp,
  ABTEILUNG varchar,
  BEREICH varchar,
  KOSTENSTELLE varchar,
  TAETIGKEIT varchar,
  RAUM varchar,
  MITARBEITERGRUPPE varchar,
  ZEITZONE varchar,
  TELEFONPRIVAT varchar,
  TELEFONFIRMA varchar,
  FAX varchar,
  FUNK varchar,
  EMAIL varchar,
  WEB varchar,
  BEGINNDATUM timestamp,
  BEGINNUHR varchar,
  ENDEDATUM timestamp,
  ENDEUHR varchar,
  PIN varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  SACHBEARBEITER_ID varchar,
  QUITTUNGSART_ID int,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  TEMP_ID int,
  RFID varchar,
  Genehmigerstatus varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_PERSONAL ON dbo.STAFF (PERSONAL_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_PERSONAL_PNR ON dbo.STAFF (PERSONALNUMMER);
CREATE INDEX IF NOT EXISTS dbo_IDX_PERSONAL_NA1 ON dbo.STAFF (NAME_1);
CREATE INDEX IF NOT EXISTS dbo_IDX_PERSONAL_NA2 ON dbo.STAFF (NAME_2);
CREATE INDEX IF NOT EXISTS dbo_IDX_PERSONAL_SU ON dbo.STAFF (SUCHBEGRIFF);

CREATE TABLE IF NOT EXISTS dbo.STAFF_GV (
  PERSONAL_GV_ID varchar PRIMARY KEY,
  PERSONAL_ID varchar,
  DBFELD varchar,
  WERT varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE TABLE IF NOT EXISTS dbo.STAFFIMAGE (
  PERSONALBILD_ID varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  BILD bytea
);

CREATE TABLE IF NOT EXISTS dbo.SYS_ADDON (
  SYS_ADDON_ID varchar PRIMARY KEY,
  SYS_ADDON_NR int,
  ART varchar,
  BESCHREIBUNG varchar,
  PROGRAMM varchar,
  CODE int,
  HINT varchar,
  A_FELD varchar,
  B_FELD varchar,
  STATUS varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_SYS_ADDON ON dbo.SYS_ADDON (SYS_ADDON_ID);

CREATE TABLE IF NOT EXISTS dbo.SYS_LOOKUPTABLE (
  SYS_NACHSCHLAGETABELLE_ID varchar PRIMARY KEY,
  SYS_NACHSCHLAGETABELLE_NR int,
  ART int,
  BEZEICHNUNG varchar,
  WERT varchar,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_SYS_NACHSCHLAGETABELLE ON dbo.SYS_LOOKUPTABLE (SYS_NACHSCHLAGETABELLE_ID);

CREATE TABLE IF NOT EXISTS dbo.SYSTEM (
  ANLAGE_ID varchar PRIMARY KEY,
  ANLAGE_NR int,
  KOMPETENZSTUFE_ID int,
  ANLAGENUMMER varchar,
  BEZEICHNUNG varchar,
  AUSGABEZONE_ID int,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  SCHLIESSANLAGE varchar,
  HERSTELLER varchar,
  ANLAGENART varchar,
  ANLAGENNUMMER varchar,
  SYSTEM varchar,
  ANLAGEANGELEGTAM timestamp,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  TEMP_ID int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_ANLAGE ON dbo.SYSTEM (ANLAGE_ID);

CREATE TABLE IF NOT EXISTS dbo.TIMEZONE (
  ZEITZONE_ID varchar PRIMARY KEY,
  ZEITZONE_NR int,
  ZEITZONENBESCHREIBUNG varchar,
  ZEITRAUM varchar,
  WOCHENTAGE varchar,
  TAGESZEIT varchar,
  D1 varchar,
  D2 varchar,
  D3 varchar,
  D4 varchar,
  D5 varchar,
  D6 varchar,
  D7 varchar,
  DATUM_VON timestamp,
  DATUM_BIS timestamp,
  ZEIT_VON varchar,
  ZEIT_BIS varchar,
  STATUS varchar,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  TEMP_ID int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_ZEITZONE ON dbo.TIMEZONE (ZEITZONE_ID);

CREATE TABLE IF NOT EXISTS dbo.TMP_PRINT (
  VORGANG_ID varchar,
  QUELL_ID varchar,
  ALTWERT_ID varchar,
  NEUWERT_ID varchar,
  ALTTEXT varchar,
  NEUTEXT varchar,
  SACHBEARBEITER_ID varchar,
  AENDERUNGSDATUM timestamp,
  ANLAGEDATUM timestamp
);

CREATE TABLE IF NOT EXISTS dbo.USER (
  BENUTZER_ID varchar PRIMARY KEY,
  BENUTZER_NR int,
  USER_KZ varchar,
  SYSTEMUSER int,
  VIPUSER int,
  NACHNAME varchar,
  VORNAME varchar,
  PASSWORT varchar,
  PERS_FRAGE varchar,
  PERS_ANTWORT varchar,
  ABTEILUNG varchar,
  RAUM varchar,
  TELEFON varchar,
  EMAIL varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  INAKTIV int,
  MENUE int,
  SACHBEARBEITER_ID varchar,
  TEMP_ID int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_BENUTZER ON dbo.USER (BENUTZER_ID);

CREATE TABLE IF NOT EXISTS dbo.VIPLEVEL (
  VIPSTUFE_ID int PRIMARY KEY,
  BEZEICHNUNG varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_VIPSTUFE ON dbo.VIPLEVEL (VIPSTUFE_ID);

ALTER TABLE dbo.RE_BUILDING_BUNDLE ADD CONSTRAINT RE_BUILDING_BUNDLE_GEBAEUDE_ID_fk FOREIGN KEY (GEBAEUDE_ID) REFERENCES dbo.BUILDING (GEBAEUDE_ID);
ALTER TABLE dbo.RE_BUILDING_BUNDLE ADD CONSTRAINT RE_BUILDING_BUNDLE_BUND_ID_fk FOREIGN KEY (BUND_ID) REFERENCES dbo.BUNDLE (BUND_ID);
ALTER TABLE dbo.RE_BUILDING_DEPOT ADD CONSTRAINT RE_BUILDING_DEPOT_GEBAEUDE_ID_fk FOREIGN KEY (GEBAEUDE_ID) REFERENCES dbo.BUILDING (GEBAEUDE_ID);
ALTER TABLE dbo.RE_BUILDING_DEPOT ADD CONSTRAINT RE_BUILDING_DEPOT_DEPOT_ID_fk FOREIGN KEY (DEPOT_ID) REFERENCES dbo.DEPOT (DEPOT_ID);
ALTER TABLE dbo.RE_BUILDING_ROLE ADD CONSTRAINT RE_BUILDING_ROLE_GEBAEUDE_ID_fk FOREIGN KEY (GEBAEUDE_ID) REFERENCES dbo.BUILDING (GEBAEUDE_ID);
ALTER TABLE dbo.RE_BUILDING_ROLE ADD CONSTRAINT RE_BUILDING_ROLE_ROLLE_ID_fk FOREIGN KEY (ROLLE_ID) REFERENCES dbo.ROLE (ROLLE_ID);
ALTER TABLE dbo.RE_BUILDING_ROLE_USER ADD CONSTRAINT RE_BUILDING_ROLE_USER_GEBAEUDE_ID_fk FOREIGN KEY (GEBAEUDE_ID) REFERENCES dbo.BUILDING (GEBAEUDE_ID);
ALTER TABLE dbo.RE_BUILDING_ROLE_USER ADD CONSTRAINT RE_BUILDING_ROLE_USER_ROLLE_ID_fk FOREIGN KEY (ROLLE_ID) REFERENCES dbo.ROLE (ROLLE_ID);
ALTER TABLE dbo.RE_BUILDING_ROLE_USER ADD CONSTRAINT RE_BUILDING_ROLE_USER_BENUTZER_ID_fk FOREIGN KEY (BENUTZER_ID) REFERENCES dbo.USER (BENUTZER_ID);
ALTER TABLE dbo.RE_BUILDING_ROLE_USER ADD CONSTRAINT RE_BUILDING_ROLE_USER_KOMPETENZSTUFE_ID_fk FOREIGN KEY (KOMPETENZSTUFE_ID) REFERENCES dbo.COMPETENCELEVEL (KOMPETENZSTUFE_ID);
ALTER TABLE dbo.RE_BUILDING_STAFF ADD CONSTRAINT RE_BUILDING_STAFF_GEBAEUDE_ID_fk FOREIGN KEY (GEBAEUDE_ID) REFERENCES dbo.BUILDING (GEBAEUDE_ID);
ALTER TABLE dbo.RE_BUILDING_STAFF ADD CONSTRAINT RE_BUILDING_STAFF_PERSONAL_ID_fk FOREIGN KEY (PERSONAL_ID) REFERENCES dbo.STAFF (PERSONAL_ID);
ALTER TABLE dbo.RE_BUNDLE_DEISTER ADD CONSTRAINT RE_BUNDLE_DEISTER_BUND_ID_fk FOREIGN KEY (BUND_ID) REFERENCES dbo.BUNDLE (BUND_ID);
ALTER TABLE dbo.RE_COPY_DEISTER ADD CONSTRAINT RE_COPY_DEISTER_EXEMPLAR_ID_fk FOREIGN KEY (EXEMPLAR_ID) REFERENCES dbo.COPY (EXEMPLAR_ID);
ALTER TABLE dbo.RE_CYLINDER_CADPLAN ADD CONSTRAINT RE_CYLINDER_CADPLAN_ZYLINDER_ID_fk FOREIGN KEY (ZYLINDER_ID) REFERENCES dbo.CYLINDER (ZYLINDER_ID);
ALTER TABLE dbo.RE_CYLINDER_CADPLAN ADD CONSTRAINT RE_CYLINDER_CADPLAN_CADPLAN_ID_fk FOREIGN KEY (CADPLAN_ID) REFERENCES dbo.CADPLAN (CADPLAN_ID);
ALTER TABLE dbo.RE_ISSUE_GV_COPY ADD CONSTRAINT RE_ISSUE_GV_COPY_AUSGABE_GV_ID_fk FOREIGN KEY (AUSGABE_GV_ID) REFERENCES dbo.ISSUE_GV (AUSGABE_GV_ID);
ALTER TABLE dbo.RE_ISSUE_GV_COPY ADD CONSTRAINT RE_ISSUE_GV_COPY_AUSGABE_ID_fk FOREIGN KEY (AUSGABE_ID) REFERENCES dbo.ISSUE (AUSGABE_ID);
ALTER TABLE dbo.RE_ISSUE_GV_COPY ADD CONSTRAINT RE_ISSUE_GV_COPY_EXEMPLAR_ID_fk FOREIGN KEY (EXEMPLAR_ID) REFERENCES dbo.COPY (EXEMPLAR_ID);
ALTER TABLE dbo.RE_ISSUE_GV_STAFF ADD CONSTRAINT RE_ISSUE_GV_STAFF_AUSGABE_GV_ID_fk FOREIGN KEY (AUSGABE_GV_ID) REFERENCES dbo.ISSUE_GV (AUSGABE_GV_ID);
ALTER TABLE dbo.RE_ISSUE_GV_STAFF ADD CONSTRAINT RE_ISSUE_GV_STAFF_AUSGABE_ID_fk FOREIGN KEY (AUSGABE_ID) REFERENCES dbo.ISSUE (AUSGABE_ID);
ALTER TABLE dbo.RE_ISSUE_GV_STAFF ADD CONSTRAINT RE_ISSUE_GV_STAFF_PERSONAL_ID_fk FOREIGN KEY (PERSONAL_ID) REFERENCES dbo.STAFF (PERSONAL_ID);
ALTER TABLE dbo.RE_KEY_CYLINDER ADD CONSTRAINT RE_KEY_CYLINDER_SCHLUESSEL_ID_fk FOREIGN KEY (SCHLUESSEL_ID) REFERENCES dbo.KEY (SCHLUESSEL_ID);
ALTER TABLE dbo.RE_KEY_CYLINDER ADD CONSTRAINT RE_KEY_CYLINDER_ZYLINDER_ID_fk FOREIGN KEY (ZYLINDER_ID) REFERENCES dbo.CYLINDER (ZYLINDER_ID);
ALTER TABLE dbo.RE_KEY_GROUP ADD CONSTRAINT RE_KEY_GROUP_SCHLUESSEL_ID_fk FOREIGN KEY (SCHLUESSEL_ID) REFERENCES dbo.KEY (SCHLUESSEL_ID);
ALTER TABLE dbo.RE_KEY_GROUP ADD CONSTRAINT RE_KEY_GROUP_GRUPPE_ID_fk FOREIGN KEY (GRUPPE_ID) REFERENCES dbo.GROUP (GRUPPE_ID);
ALTER TABLE dbo.RE_STAFF_DEISTER ADD CONSTRAINT RE_STAFF_DEISTER_PERSONAL_ID_fk FOREIGN KEY (PERSONAL_ID) REFERENCES dbo.STAFF (PERSONAL_ID);
ALTER TABLE dbo.RE_STAFF_GROUP ADD CONSTRAINT RE_STAFF_GROUP_PERSONAL_ID_fk FOREIGN KEY (PERSONAL_ID) REFERENCES dbo.STAFF (PERSONAL_ID);
ALTER TABLE dbo.RE_STAFF_GROUP ADD CONSTRAINT RE_STAFF_GROUP_GRUPPE_ID_fk FOREIGN KEY (GRUPPE_ID) REFERENCES dbo.GROUP (GRUPPE_ID);
ALTER TABLE dbo.RE_STAFF_LOCATION ADD CONSTRAINT RE_STAFF_LOCATION_PERSONAL_ID_fk FOREIGN KEY (PERSONAL_ID) REFERENCES dbo.STAFF (PERSONAL_ID);
ALTER TABLE dbo.RE_STAFF_LOCATION ADD CONSTRAINT RE_STAFF_LOCATION_STANDORT_ID_fk FOREIGN KEY (STANDORT_ID) REFERENCES dbo.LOCATION (STANDORT_ID);
ALTER TABLE dbo.RE_SYSTEM_BUILDING ADD CONSTRAINT RE_SYSTEM_BUILDING_ANLAGE_ID_fk FOREIGN KEY (ANLAGE_ID) REFERENCES dbo.SYSTEM (ANLAGE_ID);
ALTER TABLE dbo.RE_SYSTEM_BUILDING ADD CONSTRAINT RE_SYSTEM_BUILDING_GEBAEUDE_ID_fk FOREIGN KEY (GEBAEUDE_ID) REFERENCES dbo.BUILDING (GEBAEUDE_ID);
ALTER TABLE dbo.RE_SYSTEM_BUNDLE ADD CONSTRAINT RE_SYSTEM_BUNDLE_ANLAGE_ID_fk FOREIGN KEY (ANLAGE_ID) REFERENCES dbo.SYSTEM (ANLAGE_ID);
ALTER TABLE dbo.RE_SYSTEM_BUNDLE ADD CONSTRAINT RE_SYSTEM_BUNDLE_BUND_ID_fk FOREIGN KEY (BUND_ID) REFERENCES dbo.BUNDLE (BUND_ID);
ALTER TABLE dbo.RE_SYSTEM_DEPOT ADD CONSTRAINT RE_SYSTEM_DEPOT_ANLAGE_ID_fk FOREIGN KEY (ANLAGE_ID) REFERENCES dbo.SYSTEM (ANLAGE_ID);
ALTER TABLE dbo.RE_SYSTEM_DEPOT ADD CONSTRAINT RE_SYSTEM_DEPOT_DEPOT_ID_fk FOREIGN KEY (DEPOT_ID) REFERENCES dbo.DEPOT (DEPOT_ID);
ALTER TABLE dbo.RE_SYSTEM_ROLE ADD CONSTRAINT RE_SYSTEM_ROLE_ANLAGE_ID_fk FOREIGN KEY (ANLAGE_ID) REFERENCES dbo.SYSTEM (ANLAGE_ID);
ALTER TABLE dbo.RE_SYSTEM_ROLE ADD CONSTRAINT RE_SYSTEM_ROLE_ROLLE_ID_fk FOREIGN KEY (ROLLE_ID) REFERENCES dbo.ROLE (ROLLE_ID);
ALTER TABLE dbo.RE_SYSTEM_STAFF ADD CONSTRAINT RE_SYSTEM_STAFF_ANLAGE_ID_fk FOREIGN KEY (ANLAGE_ID) REFERENCES dbo.SYSTEM (ANLAGE_ID);
ALTER TABLE dbo.RE_SYSTEM_STAFF ADD CONSTRAINT RE_SYSTEM_STAFF_PERSONAL_ID_fk FOREIGN KEY (PERSONAL_ID) REFERENCES dbo.STAFF (PERSONAL_ID);
ALTER TABLE dbo.RE_SYSTEM_USER ADD CONSTRAINT RE_SYSTEM_USER_ANLAGE_ID_fk FOREIGN KEY (ANLAGE_ID) REFERENCES dbo.SYSTEM (ANLAGE_ID);
ALTER TABLE dbo.RE_SYSTEM_USER ADD CONSTRAINT RE_SYSTEM_USER_ROLLE_ID_fk FOREIGN KEY (ROLLE_ID) REFERENCES dbo.ROLE (ROLLE_ID);
ALTER TABLE dbo.RE_SYSTEM_USER ADD CONSTRAINT RE_SYSTEM_USER_BENUTZER_ID_fk FOREIGN KEY (BENUTZER_ID) REFERENCES dbo.USER (BENUTZER_ID);
ALTER TABLE dbo.RE_SYSTEM_USER ADD CONSTRAINT RE_SYSTEM_USER_KOMPETENZSTUFE_ID_fk FOREIGN KEY (KOMPETENZSTUFE_ID) REFERENCES dbo.COMPETENCELEVEL (KOMPETENZSTUFE_ID);
ALTER TABLE dbo.RE_USER_DEPOT ADD CONSTRAINT RE_USER_DEPOT_BENUTZER_ID_fk FOREIGN KEY (BENUTZER_ID) REFERENCES dbo.USER (BENUTZER_ID);
ALTER TABLE dbo.RE_USER_DEPOT ADD CONSTRAINT RE_USER_DEPOT_DEPOT_ID_fk FOREIGN KEY (DEPOT_ID) REFERENCES dbo.DEPOT (DEPOT_ID);
ALTER TABLE dbo.RE_USER_LOCATION ADD CONSTRAINT RE_USER_LOCATION_BENUTZER_ID_fk FOREIGN KEY (BENUTZER_ID) REFERENCES dbo.USER (BENUTZER_ID);
ALTER TABLE dbo.RE_USER_LOCATION ADD CONSTRAINT RE_USER_LOCATION_STANDORT_ID_fk FOREIGN KEY (STANDORT_ID) REFERENCES dbo.LOCATION (STANDORT_ID);
ALTER TABLE dbo.ORDERHEAD ADD CONSTRAINT ORDERHEAD_ANLAGE_ID_fk FOREIGN KEY (ANLAGE_ID) REFERENCES dbo.SYSTEM (ANLAGE_ID);
ALTER TABLE dbo.CYLINDERHISTORY ADD CONSTRAINT CYLINDERHISTORY_ANLAGE_ID_fk FOREIGN KEY (ANLAGE_ID) REFERENCES dbo.SYSTEM (ANLAGE_ID);
ALTER TABLE dbo.JOURNAL ADD CONSTRAINT JOURNAL_BENUTZER_ID_fk FOREIGN KEY (BENUTZER_ID) REFERENCES dbo.USER (BENUTZER_ID);
ALTER TABLE dbo.STAFF_GV ADD CONSTRAINT STAFF_GV_PERSONAL_ID_fk FOREIGN KEY (PERSONAL_ID) REFERENCES dbo.STAFF (PERSONAL_ID);
ALTER TABLE dbo.ORDERPOSITION ADD CONSTRAINT ORDERPOSITION_BESTELLKOPF_ID_fk FOREIGN KEY (BESTELLKOPF_ID) REFERENCES dbo.ORDERHEAD (BESTELLKOPF_ID);
ALTER TABLE dbo.STAFF ADD CONSTRAINT STAFF_VIPSTUFE_ID_fk FOREIGN KEY (VIPSTUFE_ID) REFERENCES dbo.VIPLEVEL (VIPSTUFE_ID);
ALTER TABLE dbo.REPORT_BIN ADD CONSTRAINT REPORT_BIN_REPORT_ID_fk FOREIGN KEY (REPORT_ID) REFERENCES dbo.REPORT (REPORT_ID);
ALTER TABLE dbo.SIGNATURE ADD CONSTRAINT SIGNATURE_PERSONAL_ID_fk FOREIGN KEY (PERSONAL_ID) REFERENCES dbo.STAFF (PERSONAL_ID);
ALTER TABLE dbo.ORDERHEAD ADD CONSTRAINT ORDERHEAD_HAENDLER_ID_fk FOREIGN KEY (HAENDLER_ID) REFERENCES dbo.DEALER (HAENDLER_ID);
ALTER TABLE dbo.GFUNCTION ADD CONSTRAINT GFUNCTION_ANLAGE_ID_fk FOREIGN KEY (ANLAGE_ID) REFERENCES dbo.SYSTEM (ANLAGE_ID);
ALTER TABLE dbo.ISSUEHISTORY ADD CONSTRAINT ISSUEHISTORY_AUSGABE_ID_fk FOREIGN KEY (AUSGABE_ID) REFERENCES dbo.ISSUE (AUSGABE_ID);
ALTER TABLE dbo.ISSUE_APP ADD CONSTRAINT ISSUE_APP_PERSONAL_ID_fk FOREIGN KEY (PERSONAL_ID) REFERENCES dbo.STAFF (PERSONAL_ID);
ALTER TABLE dbo.BUNDLE ADD CONSTRAINT BUNDLE_QUITTUNGSART_ID_fk FOREIGN KEY (QUITTUNGSART_ID) REFERENCES dbo.RECEIPTTYPE (QUITTUNGSART_ID);
ALTER TABLE dbo.BUNDLE ADD CONSTRAINT BUNDLE_EXEMPLARSTATUS_ID_fk FOREIGN KEY (EXEMPLARSTATUS_ID) REFERENCES dbo.COPYSTATUS (EXEMPLARSTATUS_ID);
ALTER TABLE dbo.COPY ADD CONSTRAINT COPY_EXEMPLARSTATUS_ID_fk FOREIGN KEY (EXEMPLARSTATUS_ID) REFERENCES dbo.COPYSTATUS (EXEMPLARSTATUS_ID);

-- GRANT ROLES FOR TOOLS
CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD 'postgres';
CREATE ROLE portier_role WITH PASSWORD 'postgres';
CREATE ROLE pmm WITH SUPERUSER ENCRYPTED PASSWORD 'postgres';

ALTER ROLE pmm WITH LOGIN;
GRANT USAGE ON SCHEMA dbo TO anon;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA dbo TO anon;

GRANT anon TO authenticator;
GRANT pg_monitor to pmm;

-- ADD TRIGGER EVENT FOR MEILISEARCH
CREATE OR REPLACE FUNCTION notify_table_change() RETURNS trigger AS $$
BEGIN
    PERFORM pg_notify('sync_notify', TG_TABLE_NAME || ':' || TG_OP);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER access_table_trigger
    AFTER INSERT OR UPDATE OR DELETE
    ON dbo.access
    FOR EACH ROW
    EXECUTE FUNCTION notify_table_change();

CREATE TRIGGER building_table_trigger
    AFTER INSERT OR UPDATE OR DELETE
    ON dbo.building
    FOR EACH ROW
    EXECUTE FUNCTION notify_table_change();

CREATE TRIGGER copy_table_trigger
    AFTER INSERT OR UPDATE OR DELETE
    ON dbo.copy
    FOR EACH ROW
    EXECUTE FUNCTION notify_table_change();

CREATE TRIGGER cylinder_table_trigger
    AFTER INSERT OR UPDATE OR DELETE
    ON dbo.cylinder
    FOR EACH ROW
    EXECUTE FUNCTION notify_table_change();

CREATE TRIGGER cylinderhistory_table_trigger
    AFTER INSERT OR UPDATE OR DELETE
    ON dbo.cylinderhistory
    FOR EACH ROW
    EXECUTE FUNCTION notify_table_change();

CREATE TRIGGER key_table_trigger
    AFTER INSERT OR UPDATE OR DELETE
    ON dbo.key
    FOR EACH ROW
    EXECUTE FUNCTION notify_table_change();

CREATE TRIGGER staff_table_trigger
    AFTER INSERT OR UPDATE OR DELETE
    ON dbo.staff
    FOR EACH ROW
    EXECUTE FUNCTION notify_table_change();

CREATE TRIGGER door_table_trigger
    AFTER INSERT OR UPDATE OR DELETE
    ON dbo.door
    FOR EACH ROW
    EXECUTE FUNCTION notify_table_change();
