CREATE SCHEMA IF NOT EXISTS dbo;

CREATE TABLE IF NOT EXISTS dbo.ANLAGE (
  ANLAGE_ID varchar PRIMARY KEY,
  ANLAGE_NR int,
  KOMPETENZSTUFE_ID int,
  ANLAGENUMMER varchar,
  BEZEICHNUNG varchar,
  AUSGABEZONE_ID int,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  SCHLIESSANLAGE varchar,
  HERSTELLER varchar,
  ANLAGENART varchar,
  ANLAGENNUMMER varchar,
  SYSTEM varchar,
  ANLAGEANGELEGTAM timestamp,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  TEMP_ID int,
  TRANSFERFLAG int,
  WERK varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_ANLAGE ON dbo.ANLAGE (ANLAGE_ID);

CREATE TABLE IF NOT EXISTS dbo.AUSFUEHRUNG (
  AUSFUEHRUNG_ID int PRIMARY KEY,
  BEZEICHNUNG varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSFUEHRUNG ON dbo.AUSFUEHRUNG (AUSFUEHRUNG_ID);

CREATE TABLE IF NOT EXISTS dbo.AUSGABE (
  AUSGABE_ID varchar PRIMARY KEY,
  EXEMPLAR_ID varchar,
  PERSONAL_ID varchar,
  BUND_ID varchar,
  SCHLUESSEL_ID varchar,
  ANLAGE_ID varchar,
  AUSGABE_NR int,
  GFUNKTION_ID varchar,
  SACHBEARBEITER_ID varchar,
  AUSGABEDATUM timestamp,
  AUSGABEUHR varchar,
  RUECKGABETERMINDATUM timestamp,
  RUECKGABETERMINUHR varchar,
  BEMERKUNG varchar,
  STATUS varchar,
  SCHLUESSELNUMMER varchar,
  AUSGABEVORGANG int,
  PENDENT int,
  UNTERSCHRIFT_ID varchar,
  PERSONAL_ID_ABHOLER varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  TEMP_ID int,
  PFAND float
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSGABE ON dbo.AUSGABE (EXEMPLAR_ID, AUSGABE_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABE_SN ON dbo.AUSGABE (SCHLUESSELNUMMER);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABE_SID ON dbo.AUSGABE (SCHLUESSEL_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABE_EID ON dbo.AUSGABE (EXEMPLAR_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABE_PID ON dbo.AUSGABE (PERSONAL_ID);

CREATE TABLE IF NOT EXISTS dbo.AUSGABE_APP (
  AUSGABE_APP_ID varchar PRIMARY KEY,
  PERSONAL_ID varchar,
  BUND_ID varchar,
  SCHLUESSEL_ID varchar,
  DEVICE_ID varchar,
  UNTERSCHRIFT_ID varchar,
  ANFRAGEDATUM timestamp,
  ANFRAGEUHR varchar,
  RUECKGABETERMINDATUM timestamp,
  RUECKGABETERMINUHR varchar,
  UNTERSCHRIFTDATUM varchar,
  UNTERSCHRIFTUHR varchar,
  STATUS varchar,
  PENDENT varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  BILDUNTERSCHRIFT varchar,
  PFAND_IST varchar,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSGABE_APP ON dbo.AUSGABE_APP (AUSGABE_APP_ID);

CREATE TABLE IF NOT EXISTS dbo.AUSGABE_GV (
  AUSGABE_GV_ID varchar PRIMARY KEY,
  AUSGABE_ID varchar,
  PERSONAL_ID varchar,
  ANFRAGEDATUM timestamp,
  ANFRAGEUHR varchar,
  GENEHMIGUNGSDATUM varchar,
  GENEHMIGUNGSUHR varchar,
  GV_PERSONAL_ID_GENEHMIGT varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  GENEHMIGUNGSART varchar,
  STATUS varchar,
  GENEHMIGUNGSVORGANG int,
  AUSGABEDOKUMENT varchar,
  FUNKTIONSDOKUMENT1 varchar,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSGABE_GV ON dbo.AUSGABE_GV (AUSGABE_GV_ID);

CREATE TABLE IF NOT EXISTS dbo.AUSGABE_SIWOS (
  AUSGABE_SIWOS_ID varchar PRIMARY KEY,
  ANTRAGS_ART varchar,
  ANTRAGSNUMMER_SIWOS varchar,
  PERSONAL_ID_ANTRAGSTELLER varchar,
  PERSONAL_NR_ANTRAGSTELLER varchar,
  PERSONAL_ID_GENEHMIGER varchar,
  PERSONAL_NR_GENEHMIGER varchar,
  PERSONAL_ID_UMSCHREIBER varchar,
  PERSONAL_NR_UMSCHREIBER varchar,
  PERSONAL_ID_ABHOLER varchar,
  PERSONAL_NR_ABHOLER varchar,
  BUND_ID varchar,
  SCHLUESSEL_ID varchar,
  EXEMPLAR_ID varchar,
  ZYLINDER_ID varchar,
  ANLAGE varchar,
  SCHLUESSELNUMMER varchar,
  EXEMPLARNUMMER int,
  AUSFUEHRUNG varchar,
  ABMESSUNG_LINKS varchar,
  ABMESSUNG_RECHTS varchar,
  FAERBUNG varchar,
  TUERNUMMER varchar,
  TUERNUMMERNEU varchar,
  RAUMBEZEICHNUNG varchar,
  RAUMBEZEICHNUNGNEU varchar,
  ANTRAGSDATUM timestamp,
  ANTRAGSUHR varchar,
  STATUS varchar,
  STATUS_MAIL varchar,
  RESERVIERUNG_BIS varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSGABE_SIWOS ON dbo.AUSGABE_SIWOS (AUSGABE_SIWOS_ID);

CREATE TABLE IF NOT EXISTS dbo.AUSGABE_SIWOS_ARCHIV (
  AUSGABE_SIWOS_ID varchar PRIMARY KEY,
  ANTRAGS_ART varchar,
  ANTRAGSNUMMER_SIWOS varchar,
  PERSONAL_ID_ANTRAGSTELLER varchar,
  PERSONAL_NR_ANTRAGSTELLER varchar,
  PERSONAL_ID_GENEHMIGER varchar,
  PERSONAL_NR_GENEHMIGER varchar,
  PERSONAL_ID_UMSCHREIBER varchar,
  PERSONAL_NR_UMSCHREIBER varchar,
  PERSONAL_ID_ABHOLER varchar,
  PERSONAL_NR_ABHOLER varchar,
  BUND_ID varchar,
  SCHLUESSEL_ID varchar,
  EXEMPLAR_ID varchar,
  ZYLINDER_ID varchar,
  ANLAGE varchar,
  SCHLUESSELNUMMER varchar,
  EXEMPLARNUMMER int,
  AUSFUEHRUNG varchar,
  ABMESSUNG_LINKS varchar,
  ABMESSUNG_RECHTS varchar,
  FAERBUNG varchar,
  TUERNUMMER varchar,
  TUERNUMMERNEU varchar,
  RAUMBEZEICHNUNG varchar,
  RAUMBEZEICHNUNGNEU varchar,
  ANTRAGSDATUM timestamp,
  ANTRAGSUHR varchar,
  STATUS varchar,
  STATUS_MAIL varchar,
  RESERVIERUNG_BIS varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  SIWOS_GEN_ID float
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSGABE_SIWOS_ARCHIV ON dbo.AUSGABE_SIWOS_ARCHIV (AUSGABE_SIWOS_ID);

CREATE TABLE IF NOT EXISTS dbo.AUSGABEHISTORIE (
  AUSGABEHISTORIE_ID varchar PRIMARY KEY,
  AUSGABE_ID varchar,
  ANLAGE_ID varchar,
  EXEMPLAR_ID varchar,
  PERSONAL_ID varchar,
  SCHLUESSEL_ID varchar,
  AUSGABEDATUM timestamp,
  AUSGABEUHR varchar,
  AUSGABE_NR int,
  BUND_ID varchar,
  SCHLUESSELNUMMER varchar,
  RUECKGABEDATUM timestamp,
  RUECKGABEUHR varchar,
  SACHBEARBEITER_ID varchar,
  SACHBEARBEITER_RUECK_ID varchar,
  BEMERKUNG varchar,
  PENDENT int,
  EXEMPLARSTATUS_ID int,
  AUSGABEVORGANG int,
  UNTERSCHRIFT_ID varchar,
  PERSONAL_ID_ABHOLER varchar,
  PFAND float
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSGABEHISTORIE ON dbo.AUSGABEHISTORIE (AUSGABEHISTORIE_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABEHISTORIE_SN ON dbo.AUSGABEHISTORIE (SCHLUESSELNUMMER);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABEHISTORIE_SID ON dbo.AUSGABEHISTORIE (SCHLUESSEL_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABEHISTORIE_EID ON dbo.AUSGABEHISTORIE (EXEMPLAR_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_AUSGABEHISTORIE_PID ON dbo.AUSGABEHISTORIE (PERSONAL_ID);

CREATE TABLE IF NOT EXISTS dbo.BENUTZER (
  BENUTZER_ID varchar PRIMARY KEY,
  BENUTZER_NR int,
  USER_KZ varchar,
  SYSTEMUSER int,
  VIPUSER int,
  NACHNAME varchar,
  VORNAME varchar,
  PASSWORT varchar,
  PERS_FRAGE varchar,
  PERS_ANTWORT varchar,
  ABTEILUNG varchar,
  RAUM varchar,
  TELEFON varchar,
  EMAIL varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  INAKTIV int,
  MENUE int,
  SACHBEARBEITER_ID varchar,
  TEMP_ID int,
  PW1 varchar,
  PW2 varchar,
  PW3 varchar,
  PW4 varchar,
  PW5 varchar,
  PW6 varchar,
  PW7 varchar,
  PW8 varchar,
  PW9 varchar,
  PWD timestamp,
  FIN_AS2_ORD boolean
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_BENUTZER ON dbo.BENUTZER (BENUTZER_ID);

CREATE TABLE IF NOT EXISTS dbo.BESTELLKOPF (
  BESTELLKOPF_ID varchar PRIMARY KEY,
  BESTELLKOPF_NR int,
  ANLAGE_ID varchar,
  HAENDLER_ID varchar,
  SACHBEARBEITER_ID varchar,
  BESTELLNUMMER varchar,
  KOMMISSIONSNUMMER varchar,
  ZUSATZ_1 varchar,
  ZUSATZ_2 varchar,
  ZUSATZ_3 varchar,
  BESTELLDATUM timestamp,
  LIEFERTERMIN timestamp,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  STATUS varchar,
  LIEFER_NAME varchar,
  LIEFER_ZUSATZ varchar,
  LIEFER_STRASSE varchar,
  LIEFER_LKZ varchar,
  LIEFER_PLZ varchar,
  LIEFER_ORT varchar,
  BESTELLART varchar,
  KUNDENNUMMER varchar,
  BUCHUNGSDATUM timestamp,
  SICHERUNGSKARTE varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  SK_Anlage varchar,
  SK_System varchar,
  SK_Anlagenart varchar,
  SK_Kartennummer varchar,
  SK_Hersteller varchar,
  SK_Ausstellungsdatum varchar,
  SK_Kartenstring varchar,
  SK_PIN varchar,
  SK_TAN varchar,
  SK_USBID varchar,
  SK_KUNDENNUMMER varchar,
  SK_HDLID varchar,
  SK_EingabeArt varchar,
  AS2_KEY varchar,
  AS2_STATUS varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_BESTELLKOPF ON dbo.BESTELLKOPF (BESTELLKOPF_ID);

CREATE TABLE IF NOT EXISTS dbo.BESTELLPOSITION (
  BESTELLPOSITION_ID varchar PRIMARY KEY,
  BESTELLPOSITION_NR int,
  BESTELLKOPF_ID varchar,
  SCHLUESSEL_ID varchar,
  ZYLINDER_ID varchar,
  SORTPOSITION smallint,
  BESTELLT smallint,
  GELIEFERT smallint,
  GESAMT smallint,
  NUMMER varchar,
  BESCHREIBUNG varchar,
  LIEFERDATUM timestamp,
  BUCHUNGSDATUM timestamp,
  ZUSATZ_1 varchar,
  ZUSATZ_2 varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  STATUS varchar,
  ZBESTELLT smallint,
  ZGELIEFERT smallint,
  ZGESAMT smallint,
  SCHLUESSELART varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_BESTELLPOSITION ON dbo.BESTELLPOSITION (BESTELLPOSITION_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_BESTELLPOSITION_SID ON dbo.BESTELLPOSITION (SCHLUESSEL_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_BESTELLPOSITION_ZID ON dbo.BESTELLPOSITION (ZYLINDER_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_BESTELLPOSITION_BID ON dbo.BESTELLPOSITION (BESTELLKOPF_ID);

CREATE TABLE IF NOT EXISTS dbo.BUND (
  BUND_ID varchar PRIMARY KEY,
  BUND_NR int,
  ANLAGE_ID varchar,
  ZEITZONE_ID varchar,
  KOMPETENZSTUFE_ID int,
  EXEMPLARSTATUS_ID int,
  SACHBEARBEITER_ID varchar,
  QUITTUNGSART_ID int,
  BUNDNUMMER varchar,
  BESCHREIBUNG varchar,
  ABTEILUNG varchar,
  BEREICH varchar,
  KOSTENSTELLE varchar,
  DEPOT_ID varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  PFAND int,
  ANSCHAFFUNG int,
  WAEHRUNG varchar,
  TEMP_ID int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_BUND ON dbo.BUND (BUND_ID);

CREATE TABLE IF NOT EXISTS dbo.CADPLAN (
  CADPLAN_ID varchar PRIMARY KEY,
  CADPLAN_NR int,
  GEBAEUDE_ID varchar,
  PLANNAME varchar,
  PFAD varchar,
  SCALE float,
  SCHRIFT_HOEHE float,
  FARBE int,
  LAYER int,
  PLAN_BLOB bytea,
  SACHBEARBEITER_ID varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_CADPLAN ON dbo.CADPLAN (CADPLAN_ID);

CREATE TABLE IF NOT EXISTS dbo.CUSTOMIZE (
  CUSTOMIZE_ID varchar PRIMARY KEY,
  CUSTOMIZE_NR int,
  BEZEICHNUNG varchar,
  WERT varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  WERT_BLOB varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_CUSTOMIZE ON dbo.CUSTOMIZE (CUSTOMIZE_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_CUSTOMIZE_BEZ ON dbo.CUSTOMIZE (BEZEICHNUNG);

CREATE TABLE IF NOT EXISTS dbo.DATEIARCHIV (
  ARCHIVE_ID varchar PRIMARY KEY,
  BESCHREIBUNG varchar,
  KATEGORIE varchar,
  STICHWORT varchar,
  DATEINAME varchar,
  DATUM timestamp,
  PERSONAL_ID varchar,
  DATEIARCHIV_PFAD varchar,
  USER_KZ varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_DATEIARCHIV ON dbo.DATEIARCHIV (ARCHIVE_ID);

CREATE TABLE IF NOT EXISTS dbo.DEPOT (
  DEPOT_ID varchar PRIMARY KEY,
  DEPOT_NR int,
  DEPOTNUMMER int,
  BEZEICHNUNG varchar,
  STRASSE varchar,
  LKZ varchar,
  PLZ varchar,
  ORT varchar,
  TELEFON varchar,
  FAX varchar,
  FUNK varchar,
  EMAIL varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  KOMPETENZSTUFE_ID int,
  STATUS int,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  TEMP_ID int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_DEPOT ON dbo.DEPOT (DEPOT_ID);

CREATE TABLE IF NOT EXISTS dbo.EXEMPLAR (
  EXEMPLAR_ID varchar PRIMARY KEY,
  EXEMPLAR_NR int,
  BUND_ID varchar,
  KOMPETENZSTUFE_ID int,
  SCHLUESSEL_ID varchar,
  RESERVIERUNG_ID varchar DEFAULT (''),
  AUSGABE_SIWOS_ID varchar DEFAULT (''),
  SCHLUESSELNUMMER varchar,
  EXEMPLARSTATUS_ID int,
  SACHBEARBEITER_ID varchar,
  DEPOT_ID varchar,
  DEPOTSTATUS int,
  SONDERBESCHRIFTUNG varchar,
  EXEMPLAR_BEZEICHNUNG varchar,
  LETZTEAENDERUNG timestamp,
  EXEMPLARNUMMER int,
  ANLAGEDATUM timestamp,
  TEMP_ID int,
  ausgabe_gv_id varchar,
  AUSGABE_APP_ID varchar,
  TRANSFERFLAG int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_EXEMPLAR ON dbo.EXEMPLAR (EXEMPLAR_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_Schluessel_ID ON dbo.EXEMPLAR (SCHLUESSEL_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_EXEMPLAR_SN ON dbo.EXEMPLAR (SCHLUESSELNUMMER);
CREATE INDEX IF NOT EXISTS dbo_IDX_EXEMPLAR_SID ON dbo.EXEMPLAR (SCHLUESSEL_ID);

CREATE TABLE IF NOT EXISTS dbo.EXEMPLARSTATUS (
  EXEMPLARSTATUS_ID int PRIMARY KEY,
  BEZEICHNUNG varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_EXEMPLARSTATUS ON dbo.EXEMPLARSTATUS (EXEMPLARSTATUS_ID);

CREATE TABLE IF NOT EXISTS dbo.GEBAEUDE (
  GEBAEUDE_ID varchar PRIMARY KEY,
  GEBAEUDE_NR int,
  BEZEICHNUNG varchar,
  GEBAEUDETEIL varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  PLZ varchar,
  ORT varchar,
  LKZ varchar,
  STRASSE varchar,
  SACHBEARBEITER_ID varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  TEMP_ID int,
  GEBAEUDE_FREMD_ID varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_GEBAEUDE ON dbo.GEBAEUDE (GEBAEUDE_ID);

CREATE TABLE IF NOT EXISTS dbo.GFUNKTION (
  GFUNKTION_ID varchar PRIMARY KEY,
  GFUNKTION_NR int,
  ANLAGE_ID varchar,
  SCHLUESSELNUMMER_DEF varchar,
  SCHLUESSELNUMMER_AUS varchar,
  SCHLUESSELNUMMER_IN varchar,
  GFUNKTION varchar,
  KZ_VERARBEITUNG varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  ZEITZONE_ID varchar,
  TEMP_ID int,
  EXTERNFLAG varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_GFUNKTION ON dbo.GFUNKTION (GFUNKTION_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_SCHLUESSELNUMMER_AUS ON dbo.GFUNKTION (SCHLUESSELNUMMER_AUS);
CREATE INDEX IF NOT EXISTS dbo_IDX_SCHLUESSELNUMMER_IN ON dbo.GFUNKTION (SCHLUESSELNUMMER_IN);
CREATE INDEX IF NOT EXISTS dbo_IDX_GFUNKTION_AID ON dbo.GFUNKTION (ANLAGE_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_GFUNKTION_AID_SNA ON dbo.GFUNKTION (ANLAGE_ID, SCHLUESSELNUMMER_AUS);
CREATE INDEX IF NOT EXISTS dbo_IDX_GFUNKTION_AID_SNI ON dbo.GFUNKTION (ANLAGE_ID, SCHLUESSELNUMMER_IN);
CREATE INDEX IF NOT EXISTS dbo_IDX_GFUNKTION_AID_SND ON dbo.GFUNKTION (ANLAGE_ID, SCHLUESSELNUMMER_DEF);

CREATE TABLE IF NOT EXISTS dbo.GRUPPE (
  GRUPPE_ID varchar PRIMARY KEY,
  GRUPPE_NR int,
  GRUPPENNUMMER int,
  BEZEICHNUNG varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  SACHBEARBEITER_ID varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_GRUPPE ON dbo.GRUPPE (GRUPPE_ID);

CREATE TABLE IF NOT EXISTS dbo.HAENDLER (
  HAENDLER_ID varchar PRIMARY KEY,
  HAENDLER_NR int,
  HAENDLERNUMMER varchar,
  KUNDENNUMMER varchar,
  NAME_1 varchar,
  NAME_2 varchar,
  ANREDE varchar,
  ZUSATZ varchar,
  STRASSE varchar,
  LKZ varchar,
  PLZ varchar,
  ORT varchar,
  TELEFON varchar,
  FUNK varchar,
  FAX varchar,
  EMAIL varchar,
  WEB varchar,
  HAENDLER_SEIT timestamp,
  NAMEANSPRECHPARTNER varchar,
  TELEFONANSPRECHPARTNER varchar,
  LETZTEBESTELLUNG timestamp,
  BEMERKUNG varchar,
  SACHBEARBEITER_ID varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  ANSPRECHPARTNER varchar,
  HDL_BEST_MAIL varchar,
  HDL_BEST_KEY varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  HDL_BEST_Heandler_ID varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_HAENDLER ON dbo.HAENDLER (HAENDLER_ID);

CREATE TABLE IF NOT EXISTS dbo.JOURNAL (
  AKTION varchar,
  TABELLE varchar,
  ID varchar,
  NR varchar,
  SPALTE varchar,
  WERT varchar,
  WERTALT varchar,
  BENUTZER_ID varchar,
  ANLAGEDATUM timestamp
);

CREATE TABLE IF NOT EXISTS dbo.KOMPETENZSTUFE (
  KOMPETENZSTUFE_ID int PRIMARY KEY,
  BEZEICHNUNG varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_KOMPETENZSTUFE ON dbo.KOMPETENZSTUFE (KOMPETENZSTUFE_ID);

CREATE TABLE IF NOT EXISTS dbo.LOGDATA (
  LOG_ID varchar PRIMARY KEY,
  ANTRAGSNUMMER_SIWOS varchar,
  SERVICECALL varchar,
  REQUESTDATE timestamp,
  REQUESTTIME varchar,
  REQUESTXML varchar,
  RESPONCEDATE timestamp,
  RESPONCETIME varchar,
  RESPONCEXML varchar,
  ERRORSTATUS varchar,
  ERRORMESSAGE varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_LOGDATA ON dbo.LOGDATA (LOG_ID);

CREATE TABLE IF NOT EXISTS dbo.PERSONAL (
  PERSONAL_ID varchar PRIMARY KEY,
  PERSONAL_NR int,
  VIPSTUFE_ID int,
  KOMPETENZSTUFE_ID int,
  PERSONALNUMMER varchar,
  SUCHBEGRIFF varchar,
  ANREDE varchar,
  NAME_1 varchar,
  NAME_2 varchar,
  ZUSATZ varchar,
  STRASSE varchar,
  LKZ varchar,
  PLZ varchar,
  ORT varchar,
  GEBURTSDATUM timestamp,
  VORLAGEDATUM timestamp,
  ABTEILUNG varchar,
  BEREICH varchar,
  KOSTENSTELLE varchar,
  TAETIGKEIT varchar,
  RAUM varchar,
  MITARBEITERGRUPPE varchar,
  ZEITZONE varchar,
  TELEFONPRIVAT varchar,
  TELEFONFIRMA varchar,
  FAX varchar,
  FUNK varchar,
  EMAIL varchar,
  WEB varchar,
  BEGINNDATUM timestamp,
  BEGINNUHR varchar,
  ENDEDATUM timestamp,
  ENDEUHR varchar,
  PIN varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  SACHBEARBEITER_ID varchar,
  QUITTUNGSART_ID int,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  TEMP_ID int,
  RFID varchar,
  Genehmigerstatus varchar,
  TRANSFERFLAG int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_PERSONAL ON dbo.PERSONAL (PERSONAL_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_PERSONAL_PNR ON dbo.PERSONAL (PERSONALNUMMER);
CREATE INDEX IF NOT EXISTS dbo_IDX_PERSONAL_NA1 ON dbo.PERSONAL (NAME_1);
CREATE INDEX IF NOT EXISTS dbo_IDX_PERSONAL_NA2 ON dbo.PERSONAL (NAME_2);
CREATE INDEX IF NOT EXISTS dbo_IDX_PERSONAL_SU ON dbo.PERSONAL (SUCHBEGRIFF);

CREATE TABLE IF NOT EXISTS dbo.PERSONAL_GV (
  PERSONAL_GV_ID varchar PRIMARY KEY,
  PERSONAL_ID varchar,
  DBFELD varchar,
  WERT varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_PERSONAL_GV ON dbo.PERSONAL_GV (PERSONAL_GV_ID);

CREATE TABLE IF NOT EXISTS dbo.PERSONALBILD (
  PERSONALBILD_ID varchar PRIMARY KEY,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  BILD bytea
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_PERSONALBILD ON dbo.PERSONALBILD (PERSONALBILD_ID);

CREATE TABLE IF NOT EXISTS dbo.QUICK_QUERIES (
  QUICK_QUERY_ID int PRIMARY KEY,
  BENUTZER_ID varchar,
  ANLAGE_ID varchar,
  GEBAEUDE_ID varchar,
  ART varchar,
  QUERY_NAME varchar,
  QUERY_PARAMS varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_QUICK_QUERIES ON dbo.QUICK_QUERIES (QUICK_QUERY_ID);

CREATE TABLE IF NOT EXISTS dbo.QUITTUNGSART (
  QUITTUNGSART_ID int PRIMARY KEY,
  BEZEICHNUNG varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_QUITTUNGSART ON dbo.QUITTUNGSART (QUITTUNGSART_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_ANLAGE_BUND (
  ANLAGE_ID varchar,
  BUND_ID varchar,
  PRIMARY KEY (ANLAGE_ID, BUND_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_ANLAGE_BUND ON dbo.RE_ANLAGE_BUND (ANLAGE_ID, BUND_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_ANLAGE_DEPOT (
  ANLAGE_ID varchar,
  DEPOT_ID varchar,
  PRIMARY KEY (ANLAGE_ID, DEPOT_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_ANLAGE_DEPOT ON dbo.RE_ANLAGE_DEPOT (ANLAGE_ID, DEPOT_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_ANLAGE_GEBAEUDE (
  ANLAGE_ID varchar,
  GEBAEUDE_ID varchar,
  PRIMARY KEY (ANLAGE_ID, GEBAEUDE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_ANLAGE_GEBAEUDE ON dbo.RE_ANLAGE_GEBAEUDE (ANLAGE_ID, GEBAEUDE_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_ANLAGE_PERSONAL (
  ANLAGE_ID varchar,
  PERSONAL_ID varchar,
  PRIMARY KEY (ANLAGE_ID, PERSONAL_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_ANLAGE_PERSONAL ON dbo.RE_ANLAGE_PERSONAL (ANLAGE_ID, PERSONAL_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_ANLAGE_ROLLE (
  ANLAGE_ID varchar,
  ROLLE_ID varchar,
  PRIMARY KEY (ANLAGE_ID, ROLLE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_ANLAGE_ROLLE ON dbo.RE_ANLAGE_ROLLE (ANLAGE_ID, ROLLE_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_ANLAGE_ROLLE_BENUTZER (
  ANLAGE_ID varchar,
  ROLLE_ID varchar,
  BENUTZER_ID varchar,
  KOMPETENZSTUFE_ID int,
  PRIMARY KEY (ANLAGE_ID, ROLLE_ID, BENUTZER_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_ANLAGE_ROLLE_BENUTZER ON dbo.RE_ANLAGE_ROLLE_BENUTZER (ANLAGE_ID, ROLLE_ID, BENUTZER_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_AUSGABE_GV_EXEMPLAR (
  AUSGABE_GV_ID varchar,
  AUSGABE_ID varchar,
  EXEMPLAR_ID varchar,
  PRIMARY KEY (AUSGABE_GV_ID, AUSGABE_ID, EXEMPLAR_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSGABE_GV_EXEMPLAR ON dbo.RE_AUSGABE_GV_EXEMPLAR (AUSGABE_GV_ID, AUSGABE_ID, EXEMPLAR_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_AUSGABE_GV_PERSONAL (
  AUSGABE_GV_ID varchar,
  AUSGABE_ID varchar,
  PERSONAL_ID varchar,
  PRIMARY KEY (AUSGABE_GV_ID, AUSGABE_ID, PERSONAL_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_AUSGABE_GV_PERSONAL ON dbo.RE_AUSGABE_GV_PERSONAL (AUSGABE_GV_ID, AUSGABE_ID, PERSONAL_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_BENUTZER_DEPOT (
  BENUTZER_ID varchar,
  DEPOT_ID varchar,
  PRIMARY KEY (DEPOT_ID, BENUTZER_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_BENUTZER_DEPOT ON dbo.RE_BENUTZER_DEPOT (DEPOT_ID, BENUTZER_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_BENUTZER_STANDORT (
  BENUTZER_ID varchar,
  STANDORT_ID varchar,
  PRIMARY KEY (BENUTZER_ID, STANDORT_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_BENUTZER_STANDORT ON dbo.RE_BENUTZER_STANDORT (BENUTZER_ID, STANDORT_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_BENUTZER_TILE_STRUCTURE (
  TILE_ID int PRIMARY KEY,
  BENUTZER_ID varchar,
  ANLAGE_GEBAUDE_ID varchar,
  ANLAGE_GEBAUDE_BEZEICHNUNG varchar,
  SYSTEMUSER int DEFAULT (0),
  ROLLE_ID varchar,
  TILE_STRUCTURE varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK__RE_BENUT__411A8FC975A83D7A ON dbo.RE_BENUTZER_TILE_STRUCTURE (TILE_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_BUND_DEISTER (
  BUND_ID varchar PRIMARY KEY,
  BUND_NR int,
  KEYTAG_ID int,
  CABINET_ID int,
  SLOT_NUMBER int,
  TRANSPONDERSTATE int,
  TERMINAL_DISPLAYNAME varchar,
  MAKE varchar,
  MODEL varchar,
  SERIALNUMBER varchar,
  RESPONSIBLEEMAIL varchar,
  CURRENTTERMINALUSERIDKEEPER int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_BUND_DEISTER ON dbo.RE_BUND_DEISTER (BUND_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_EXEMPLAR_DEISTER (
  EXEMPLAR_ID varchar PRIMARY KEY,
  EXEMPLAR_NR int,
  CABINET_ID int,
  SLOT_NUMBER int,
  TRANSPONDERSTATE int,
  KEYTAG_ID int,
  TERMINAL_DISPLAYNAME varchar,
  MAKE varchar,
  MODEL varchar,
  SERIALNUMBER varchar,
  RESPONSIBLEEMAIL varchar,
  CURRENTTERMINALUSERIDKEEPER int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_EXEMPLAR_DEISTER ON dbo.RE_EXEMPLAR_DEISTER (EXEMPLAR_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_GEBAEUDE_BUND (
  GEBAEUDE_ID varchar,
  BUND_ID varchar,
  PRIMARY KEY (BUND_ID, GEBAEUDE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_GEBAEUDE_BUND ON dbo.RE_GEBAEUDE_BUND (BUND_ID, GEBAEUDE_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_GEBAEUDE_DEPOT (
  GEBAEUDE_ID varchar,
  DEPOT_ID varchar,
  PRIMARY KEY (DEPOT_ID, GEBAEUDE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_GEBAEUDE_DEPOT ON dbo.RE_GEBAEUDE_DEPOT (DEPOT_ID, GEBAEUDE_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_GEBAEUDE_PERSONAL (
  GEBAEUDE_ID varchar,
  PERSONAL_ID varchar,
  PRIMARY KEY (GEBAEUDE_ID, PERSONAL_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_GEBAEUDE_PERSONAL ON dbo.RE_GEBAEUDE_PERSONAL (GEBAEUDE_ID, PERSONAL_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_GEBAEUDE_ROLLE (
  GEBAEUDE_ID varchar,
  ROLLE_ID varchar,
  PRIMARY KEY (GEBAEUDE_ID, ROLLE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_GEBAEUDE_ROLLE ON dbo.RE_GEBAEUDE_ROLLE (GEBAEUDE_ID, ROLLE_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_GEBAEUDE_ROLLE_BENUTZER (
  GEBAEUDE_ID varchar,
  ROLLE_ID varchar,
  BENUTZER_ID varchar,
  KOMPETENZSTUFE_ID int,
  PRIMARY KEY (GEBAEUDE_ID, ROLLE_ID, BENUTZER_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_GEBAEUDE_ROLLE_BENUTZER ON dbo.RE_GEBAEUDE_ROLLE_BENUTZER (GEBAEUDE_ID, ROLLE_ID, BENUTZER_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_PERSONAL_DEISTER (
  TERMINAL_USER_ID int,
  PERSONAL_DEISTER_NR int PRIMARY KEY,
  PERSONAL_ID varchar,
  PERSONAL_NR int,
  TERMINAL_ANZEIGE varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_PERSONAL_DEISTER ON dbo.RE_PERSONAL_DEISTER (PERSONAL_DEISTER_NR);

CREATE TABLE IF NOT EXISTS dbo.RE_PERSONAL_GRUPPE (
  PERSONAL_ID varchar,
  GRUPPE_ID varchar,
  PRIMARY KEY (PERSONAL_ID, GRUPPE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_PERSONAL_GRUPPE ON dbo.RE_PERSONAL_GRUPPE (PERSONAL_ID, GRUPPE_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_PERSONAL_STANDORT (
  PERSONAL_ID varchar,
  STANDORT_ID varchar,
  PRIMARY KEY (PERSONAL_ID, STANDORT_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_PERSONAL_STANDORT ON dbo.RE_PERSONAL_STANDORT (PERSONAL_ID, STANDORT_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_SCHLUESSEL_GRUPPE (
  SCHLUESSEL_ID varchar,
  GRUPPE_ID varchar,
  PRIMARY KEY (SCHLUESSEL_ID, GRUPPE_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_SCHLUESSEL_GRUPPE ON dbo.RE_SCHLUESSEL_GRUPPE (SCHLUESSEL_ID, GRUPPE_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_SCHLUESSEL_ZYLINDER (
  SCHLUESSEL_ID varchar,
  ZYLINDER_ID varchar,
  PRIMARY KEY (SCHLUESSEL_ID, ZYLINDER_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_SCHLUESSEL_ZYLINDER ON dbo.RE_SCHLUESSEL_ZYLINDER (SCHLUESSEL_ID, ZYLINDER_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_RE_SCHLUESSEL_ZYLINDER_SID_ZID ON dbo.RE_SCHLUESSEL_ZYLINDER (SCHLUESSEL_ID, ZYLINDER_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_RE_SCHLUESSEL_ZYLINDER_SID ON dbo.RE_SCHLUESSEL_ZYLINDER (SCHLUESSEL_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_RE_SCHLUESSEL_ZYLINDER_ZID ON dbo.RE_SCHLUESSEL_ZYLINDER (ZYLINDER_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_TUER_ZYLINDER (
  TUER_ID varchar,
  ZYLINDER_ID varchar,
  PRIMARY KEY (TUER_ID, ZYLINDER_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_TUER_ZYLINDER ON dbo.RE_TUER_ZYLINDER (TUER_ID, ZYLINDER_ID);

CREATE TABLE IF NOT EXISTS dbo.RE_ZYLINDER_CADPLAN (
  ZYLINDER_ID varchar,
  CADPLAN_ID varchar,
  PRIMARY KEY (CADPLAN_ID, ZYLINDER_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_RE_ZYLINDER_CADPLAN ON dbo.RE_ZYLINDER_CADPLAN (CADPLAN_ID, ZYLINDER_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_RE_ZYLINDER_CADPLAN_ZID_CID ON dbo.RE_ZYLINDER_CADPLAN (ZYLINDER_ID, CADPLAN_ID);

CREATE TABLE IF NOT EXISTS dbo.REPORT (
  REPORT_ID varchar PRIMARY KEY,
  REPORT_NR int,
  REPORTART int,
  GRUPPE varchar,
  NAME varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  STEUERUNG int,
  REPORT_AENDERBAR int,
  SQL_TEXT varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  REPORTNUMMER varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_REPORT ON dbo.REPORT (REPORT_ID);

CREATE TABLE IF NOT EXISTS dbo.REPORT_BIN (
  REPORT_BIN_ID varchar PRIMARY KEY,
  REPORT_BIN_NR int,
  REPORT_ID varchar,
  SPRACHE_ID int,
  BESCHREIBUNG varchar,
  REPORT_PFAD varchar,
  REPORT_BIN bytea,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  SACHBEARBEITER_ID varchar,
  REPORT_VARIANTE int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_REPORT_BIN ON dbo.REPORT_BIN (REPORT_BIN_ID);

CREATE TABLE IF NOT EXISTS dbo.ROLLE (
  ROLLE_ID varchar PRIMARY KEY,
  ROLLE_NR int,
  STUFE int,
  BEZEICHNUNG varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_ROLLE ON dbo.ROLLE (ROLLE_ID);

CREATE TABLE IF NOT EXISTS dbo.SCHLIESSMATRIX (
  SCHLIESSMATRIX_ID varchar PRIMARY KEY,
  NUMMER int,
  SCHLIESSMATRIX_NR int,
  BESCHREIBUNG varchar,
  PERIODISCH varchar,
  DATUMFLAG varchar,
  DATUM_SET text,
  TIME_SET text,
  FEIER_SET text,
  SACHBEARBEITER_ID varchar,
  STATUS varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  TEMP_ID int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_SCHLIESSMATRIX ON dbo.SCHLIESSMATRIX (SCHLIESSMATRIX_ID);

CREATE TABLE IF NOT EXISTS dbo.SCHLUESSEL (
  SCHLUESSEL_ID varchar PRIMARY KEY,
  SCHLUESSEL_NR int,
  ANLAGE_ID varchar,
  ZEITZONE_ID varchar,
  KOMPETENZSTUFE_ID int,
  UE_KNOTEN int,
  SCHLUESSELNUMMER varchar,
  SCHLUESSELNUMMER_ZUSATZ varchar,
  SCHLUESSELBESCHREIBUNG varchar,
  SCHLUESSELNAME varchar,
  SCHLUESSELART smallint,
  SCHLIESSUNGSART smallint,
  SCHLUESSELTYP smallint,
  MINDESTBESTAND int,
  BESTELLVORSCHLAG int,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  ARTIKEL_NR varchar,
  SACHBEARBEITER_ID varchar,
  SORTIERUNG int,
  SONDERBESCHRIFTUNG varchar,
  DEPOTFREMD int,
  QUITTUNGSART_ID int,
  PFAND int,
  ANSCHAFFUNG int,
  WAEHRUNG varchar,
  TEMP_ID int,
  ERWEITERUNG int,
  SCHLUESSEL_FREMD_ID varchar,
  PIN varchar,
  WERK varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  EXTERNFLAG varchar,
  Sensitiv varchar,
  GenehmigungsFlag varchar,
  TRANSFERFLAG int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_SCHLUESSEL ON dbo.SCHLUESSEL (SCHLUESSEL_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_SCHLUESSEL_SN ON dbo.SCHLUESSEL (SCHLUESSELNUMMER);
CREATE INDEX IF NOT EXISTS dbo_IDX_SCHLUESSEL_BES ON dbo.SCHLUESSEL (SCHLUESSELBESCHREIBUNG);
CREATE INDEX IF NOT EXISTS dbo_IDX_SCHLUESSEL_AID ON dbo.SCHLUESSEL (ANLAGE_ID);

CREATE TABLE IF NOT EXISTS dbo.SCHLUESSEL_SIWOS_DELTA (
  SCHLUESSEL_ID varchar PRIMARY KEY,
  WERK varchar,
  HERSTELLER varchar,
  SCHLIESSANLAGE varchar,
  SCHLUESSELNUMMER varchar,
  STATUS varchar,
  TRANSFERFLAG int,
  TRANSFERFLAGANLAGE int,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_SCHLUESSEL_SIWOS_DELTA ON dbo.SCHLUESSEL_SIWOS_DELTA (SCHLUESSEL_ID);

CREATE TABLE IF NOT EXISTS dbo.STANDORT (
  STANDORT_ID varchar PRIMARY KEY,
  STANDORT_NR int,
  STANDORTNUMMER int,
  BEZEICHNUNG varchar,
  STRASSE varchar,
  LKZ varchar,
  PLZ varchar,
  ORT varchar,
  TELEFON varchar,
  FAX varchar,
  FUNK varchar,
  EMAIL varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  STATUS int,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  TEMP_ID int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_STANDORT ON dbo.STANDORT (STANDORT_ID);

CREATE TABLE IF NOT EXISTS dbo.SYS_ADDON (
  SYS_ADDON_ID varchar PRIMARY KEY,
  SYS_ADDON_NR int,
  ART varchar,
  BESCHREIBUNG varchar,
  PROGRAMM varchar,
  CODE int,
  HINT varchar,
  A_FELD varchar,
  B_FELD varchar,
  STATUS varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_SYS_ADDON ON dbo.SYS_ADDON (SYS_ADDON_ID);

CREATE TABLE IF NOT EXISTS dbo.SYS_NACHSCHLAGETABELLE (
  SYS_NACHSCHLAGETABELLE_ID varchar PRIMARY KEY,
  SYS_NACHSCHLAGETABELLE_NR int,
  ART int,
  BEZEICHNUNG varchar,
  WERT varchar,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_SYS_NACHSCHLAGETABELLE ON dbo.SYS_NACHSCHLAGETABELLE (SYS_NACHSCHLAGETABELLE_ID);

CREATE TABLE IF NOT EXISTS dbo.TMP_DRUCK (
  VORGANG_ID varchar,
  QUELL_ID varchar,
  ALTWERT_ID varchar,
  NEUWERT_ID varchar,
  ALTTEXT varchar,
  NEUTEXT varchar,
  SACHBEARBEITER_ID varchar,
  AENDERUNGSDATUM timestamp,
  ANLAGEDATUM timestamp,
  PRIMARY KEY (VORGANG_ID, QUELL_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_TMP_DRUCK ON dbo.TMP_DRUCK (VORGANG_ID, QUELL_ID);

CREATE TABLE IF NOT EXISTS dbo.TUER (
  TUER_ID varchar PRIMARY KEY,
  GEBAEUDE_ID varchar,
  TUER_NR int,
  BEZEICHNUNG varchar,
  KURZNOTIZ varchar,
  TUERNR varchar,
  TUERNRELEKTRISCH varchar,
  RAUMBEZEICHNUNG varchar,
  ABTEILUNG varchar,
  BEREICH varchar,
  KOSTENSTELLE varchar,
  ZUSATZ1 varchar,
  ZUSATZ2 varchar,
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  EINBAUSTATUS int,
  TEMP_ID int,
  TUER_FREMD_ID varchar,
  SACHBEARBEITER_ID varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_TUER ON dbo.TUER (TUER_ID);

CREATE TABLE IF NOT EXISTS dbo.UNTERSCHRIFT (
  UNTERSCHRIFT_ID varchar PRIMARY KEY,
  UNTERSCHRIFT_NR int,
  PERSONAL_ID varchar,
  SACHBEARBEITER_ID varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  BILD bytea
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_UNTERSCHRIFT ON dbo.UNTERSCHRIFT (UNTERSCHRIFT_ID);

CREATE TABLE IF NOT EXISTS dbo.VIPSTUFE (
  VIPSTUFE_ID int PRIMARY KEY,
  BEZEICHNUNG varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_VIPSTUFE ON dbo.VIPSTUFE (VIPSTUFE_ID);

CREATE TABLE IF NOT EXISTS dbo.ZEITZONE (
  ZEITZONE_ID varchar PRIMARY KEY,
  ZEITZONE_NR int,
  ZEITZONENBESCHREIBUNG varchar,
  ZEITRAUM varchar,
  WOCHENTAGE varchar,
  TAGESZEIT varchar,
  D1 varchar,
  D2 varchar,
  D3 varchar,
  D4 varchar,
  D5 varchar,
  D6 varchar,
  D7 varchar,
  DATUM_VON timestamp,
  DATUM_BIS timestamp,
  ZEIT_VON varchar,
  ZEIT_BIS varchar,
  STATUS varchar,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp,
  TEMP_ID int
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_ZEITZONE ON dbo.ZEITZONE (ZEITZONE_ID);

CREATE TABLE IF NOT EXISTS dbo.ZUGRIFF (
  ZUGRIFF_ID varchar PRIMARY KEY,
  ZUGRIFF_NR int,
  GRUPPE varchar,
  AKTION varchar,
  STUFE int,
  KOMPETENZ int,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_ZUGRIFF ON dbo.ZUGRIFF (ZUGRIFF_ID);

CREATE TABLE IF NOT EXISTS dbo.ZYLINDER (
  ZYLINDER_ID varchar PRIMARY KEY,
  ZYLINDER_NR int,
  ANLAGE_ID varchar,
  GEBAEUDE_ID varchar,
  CADPLAN_ID varchar,
  KOMPETENZSTUFE_ID int,
  AUSFUEHRUNG_ID int,
  SCHLUESSELNUMMER varchar,
  BEZEICHNUNG varchar,
  GPOSITION varchar,
  ZYLINDERANZAHL int,
  KURZNOTIZ varchar,
  BESTELLVORSCHLAG int,
  TUERNR varchar,
  RAUMBEZEICHNUNG varchar,
  ABTEILUNG varchar,
  BEREICH varchar,
  KOSTENSTELLE varchar,
  FAERBUNG varchar,
  TUERNRELEKTRISCH varchar,
  ZUSATZ1 varchar,
  ZUSATZ2 varchar,
  ABMESSUNG varchar,
  ABMESSUNG_LINKS numeric(6, 1),
  ABMESSUNG_RECHTS numeric(6, 1),
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  EINBAUSTATUS int,
  ARTIKEL_NR varchar,
  SORTIERUNG numeric(8, 2),
  SONDERAUSFUEHRUNG varchar,
  SONDERAUSFUEHRUNG_POS varchar,
  SONDER_POS varchar,
  XWERT float,
  YWERT float,
  ZWERT float,
  SACHBEARBEITER_ID varchar,
  PFAND numeric(8, 2),
  ANSCHAFFUNG numeric(8, 2),
  WAEHRUNG varchar,
  TEMP_ID int,
  ERWEITERUNG int,
  ZYLINDER_FREMD_ID varchar,
  WERK varchar,
  LETZTEAENDERUNG timestamp,
  ANLAGEDATUM timestamp,
  ARTIKELBESCHREIBUNG varchar,
  EXTERNFLAG varchar,
  TRANSFERFLAG int,
  SCHLUESSEL_ID varchar DEFAULT ('')
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_ZYLINDER ON dbo.ZYLINDER (ZYLINDER_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDER_SN ON dbo.ZYLINDER (SCHLUESSELNUMMER);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDER_BEZ ON dbo.ZYLINDER (BEZEICHNUNG);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDER_AID ON dbo.ZYLINDER (ANLAGE_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDER_GID ON dbo.ZYLINDER (GEBAEUDE_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDER_TNR ON dbo.ZYLINDER (TUERNR);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDER_RAU ON dbo.ZYLINDER (RAUMBEZEICHNUNG);

CREATE TABLE IF NOT EXISTS dbo.ZYLINDER_SIWOS_DELTA (
  ZYLINDER_ID varchar PRIMARY KEY,
  WERK varchar,
  SCHLIESSANLAGE varchar,
  SCHLUESSELNUMMER varchar,
  STATUS varchar,
  TRANSFERFLAG int,
  TRANSFERFLAGANLAGE int,
  ANLAGEDATUM timestamp,
  LETZTEAENDERUNG timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS dbo_PK_ZYLINDER_SIWOS_DELTA ON dbo.ZYLINDER_SIWOS_DELTA (ZYLINDER_ID);

CREATE TABLE IF NOT EXISTS dbo.ZYLINDERHISTORIE (
  ZYLINDER_ID varchar,
  ZYLINDER_NR int,
  ANLAGE_ID varchar,
  GEBAEUDE_ID varchar,
  KOMPETENZSTUFE_ID int,
  AUSFUEHRUNG_ID int,
  BEZEICHNUNG varchar,
  GPOSITION varchar,
  ZYLINDERANZAHL int,
  KURZNOTIZ varchar,
  BESTELLVORSCHLAG int,
  TUERNR varchar,
  RAUMBEZEICHNUNG varchar,
  ABTEILUNG varchar,
  BEREICH varchar,
  KOSTENSTELLE varchar,
  FAERBUNG varchar,
  TUERNRELEKTRISCH varchar,
  ZUSATZ1 varchar,
  ZUSATZ2 varchar,
  ABMESSUNG varchar,
  ABMESSUNG_LINKS numeric(6, 1),
  ABMESSUNG_RECHTS numeric(6, 1),
  BEMERKUNG_1 varchar,
  BEMERKUNG_2 varchar,
  BEMERKUNG_3 varchar,
  EINBAUSTATUS int,
  ARTIKEL_NR varchar,
  SORTIERUNG numeric(8, 2),
  SONDERAUSFUEHRUNG varchar,
  SONDERAUSFUEHRUNG_POS varchar,
  SONDER_POS varchar,
  XWERT int,
  YWERT int,
  SACHBEARBEITER_ID varchar,
  ANLAGEDATUM timestamp,
  PFAND numeric(8, 2),
  ANSCHAFFUNG numeric(8, 2),
  WAEHRUNG varchar
);

CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDERHISTORIE_ZID ON dbo.ZYLINDERHISTORIE (ZYLINDER_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDERHISTORIE_AID ON dbo.ZYLINDERHISTORIE (ANLAGE_ID);
CREATE INDEX IF NOT EXISTS dbo_IDX_ZYLINDERHISTORIE_GID ON dbo.ZYLINDERHISTORIE (GEBAEUDE_ID);